using Base: operator_associativity

include("axistensors.jl")
include("data1d.jl")
include("data1dx.jl")
include("data2d.jl")
include("data2dx.jl")
include("diffusion2d.jl")
include("fdspaces.jl")
include("field.jl")
include("fielddiffeq.jl")
include("geometry.jl")
include("grid.jl")
include("grid2d.jl")
include("grid2d_cs.jl")
include("hybrid2d.jl")
include("hybrid3d.jl")
include("hyperdiffusion_sphere.jl")
include("quadrature.jl")
include("recursive.jl")
include("spaces.jl")
include("spectraloperators.jl")
include("sphere.jl")
include("sphere_diffusion.jl")
include("sphere_metric_terms.jl")

if "CUDA" in ARGS
    include("gpu/cuda.jl")
    include("gpu/data.jl")
end
