"""
    AbstractOperator

Supertype for ClimaCore operators. An operator is a pseudo-function: it cannot be
called directly, but can be broadcasted over `Field`s. Subtypes are
[`FiniteDifferenceOperator`](@ref) and [`SpectralElementOperator`](@ref).
"""
abstract type AbstractOperator end

"""
    AbstractBoundaryCondition

Supertype for the boundary conditions of both the finite-difference and the
discontinuous-Galerkin operators. The two families act on different mesh
directions, so every boundary condition is either a
[`VerticalBoundaryCondition`](@ref) or a
[`HorizontalBoundaryCondition`](@ref), never both.
"""
abstract type AbstractBoundaryCondition end

"""
    VerticalBoundaryCondition <: AbstractBoundaryCondition

Supertype for the boundary conditions of the vertical (column)
[`FiniteDifferenceOperator`](@ref)s, e.g. [`SetValue`](@ref) and
[`Extrapolate`](@ref). Subtypes should define:

  - [`boundary_width`](@ref)
  - [`stencil_left_boundary`](@ref)
  - [`stencil_right_boundary`](@ref)
"""
abstract type VerticalBoundaryCondition <: AbstractBoundaryCondition end

"""
    HorizontalBoundaryCondition <: AbstractBoundaryCondition

Supertype for the boundary conditions of the horizontal DG numerical-flux
operators (see [`add_numerical_flux_boundary!`](@ref)), e.g.
[`ReflectingWallBC`](@ref). Subtypes should define [`ghost_state`](@ref).
"""
abstract type HorizontalBoundaryCondition <: AbstractBoundaryCondition end

"""
    return_eltype(::Op, fields...)

Return the element type of the `Field` generated by an [`AbstractOperator`](@ref)
when applied to the given `fields`.
"""
function return_eltype end

"""
    return_space(::Op, spaces...)

Return the space (axes) of the `Field` generated by an [`AbstractOperator`](@ref)
when applied to fields on the given `spaces`.
"""
function return_space end

const NonPointwiseBroadcasted =
    Broadcast.Broadcasted{<:Fields.AbstractFieldStyle, <:Any, <:AbstractOperator}

# The arguments of a non-pointwise broadcast can have spaces that differ from
# the result's space (e.g., an F2C operator reads from a face space and writes
# to a center space), so they cannot be verified through check_broadcast_space.
shared_space_field(bc) = Fields.local_geometry_field(Fields.shared_space(bc))

Utilities.unsafe_eltype((; f, args)::NonPointwiseBroadcasted) =
    return_eltype(f, args...)
@inline Fields.shared_space((; f, args)::NonPointwiseBroadcasted) =
    return_space(f, unrolled_map(axes, args)...)
@inline Fields.check_broadcast_space(space, bc::NonPointwiseBroadcasted, only_check_size) =
    Fields.check_broadcast_space(space, shared_space_field(bc), only_check_size)
@inline Broadcast.instantiate((; style, f, args, axes)::NonPointwiseBroadcasted) =
    Broadcast.Broadcasted(style, f, unrolled_map(Broadcast.instantiate, args), axes)

# TODO: Remove this after refactoring the StencilBroadcasted API.
abstract type OperatorBroadcasted{Style} <: Base.AbstractBroadcasted end

Base.Broadcast.BroadcastStyle(
    ::Type{<:OperatorBroadcasted{Style}},
) where {Style} = Style()

@inline DataLayouts.DataScope(opbc::OperatorBroadcasted) =
    DataLayouts.DataScope(unrolled_filter(Fields.has_field_style, opbc.args)...)
@inline Fields.shared_space(opbc::OperatorBroadcasted) =
    return_space(opbc.op, unrolled_map(axes, opbc.args)...)
@inline Fields.check_broadcast_space(space, opbc::OperatorBroadcasted, only_check_size) =
    Fields.check_broadcast_space(space, shared_space_field(opbc), only_check_size)

Base.axes(opbc::OperatorBroadcasted) =
    isnothing(opbc.axes) ? Fields.shared_space(opbc) : opbc.axes
Base.Broadcast.broadcastable(opbc::OperatorBroadcasted) = opbc
Base.copy(opbc::OperatorBroadcasted) = copyto!(similar(opbc), opbc)
Base.similar(opbc::OperatorBroadcasted, ::Type{Eltype}) where {Eltype} =
    Field(Eltype, axes(opbc))

# Define similar to match DataStyle and AbstractFieldStyle broadcasting
Base.similar(opbc::OperatorBroadcasted) =
    similar(opbc, drop_auto_broadcasters(eltype(opbc)))

function Base.Broadcast.materialize(opbc::OperatorBroadcasted)
    copy(Base.Broadcast.instantiate(opbc))
end

function Base.Broadcast.materialize!(dest, opbc::OperatorBroadcasted)
    copyto!(dest, Base.Broadcast.instantiate(opbc))
end
