import UnrolledUtilities: unrolled_map

"""
    AbstractOperator

Supertype for ClimaCore operators. An operator is a pseudo-function: it can't be
called directly, but can be broadcasted over `Field`s.
"""
abstract type AbstractOperator end

"""
    AbstractBoundaryCondition

Supertype for the boundary conditions of both the finite-difference and the
discontinuous-Galerkin operators. The two families act on different mesh
directions, so every boundary condition is either a
[`VerticalBoundaryCondition`](@ref) or a
[`HorizontalBoundaryCondition`](@ref), never both.
"""
abstract type AbstractBoundaryCondition end

"""
    VerticalBoundaryCondition <: AbstractBoundaryCondition

Supertype for the boundary conditions of the vertical (column)
[`FiniteDifferenceOperator`](@ref)s, e.g. [`SetValue`](@ref) and
[`Extrapolate`](@ref). Subtypes should define:

  - [`boundary_width`](@ref)
  - [`stencil_left_boundary`](@ref)
  - [`stencil_right_boundary`](@ref)
"""
abstract type VerticalBoundaryCondition <: AbstractBoundaryCondition end

"""
    HorizontalBoundaryCondition <: AbstractBoundaryCondition

Supertype for the boundary conditions of the horizontal DG numerical-flux
operators (see [`add_numerical_flux_boundary!`](@ref)), e.g.
[`ReflectingWallBC`](@ref). Subtypes should define [`ghost_state`](@ref).
"""
abstract type HorizontalBoundaryCondition <: AbstractBoundaryCondition end

"""
    return_eltype(::Op, fields...)

Element type of the `Field` generated by an [`AbstractOperator`](@ref) when
applied to the given `fields`.
"""
function return_eltype end

"""
    return_space(::Op, spaces...)

Axes of the `Field` generated by an [`AbstractOperator`](@ref) when applied to
fields on the given `spaces`.
"""
function return_space end

const NonPointwiseBroadcasted =
    Broadcast.Broadcasted{<:Fields.AbstractFieldStyle, <:Any, <:AbstractOperator}

Utilities.unsafe_eltype((; f, args)::NonPointwiseBroadcasted) =
    return_eltype(f, args...)
Broadcast._axes((; f, args)::NonPointwiseBroadcasted, ::Nothing) =
    return_space(f, unrolled_tuple_map(axes, args)...)
Broadcast.instantiate((; style, f, args, axes)::NonPointwiseBroadcasted) =
    Broadcast.Broadcasted(style, f, unrolled_tuple_map(Broadcast.instantiate, args), axes)

# TODO: Remove this after refactoring the StencilBroadcasted API.
abstract type OperatorBroadcasted{Style} <: Base.AbstractBroadcasted end

Base.Broadcast.BroadcastStyle(
    ::Type{<:OperatorBroadcasted{Style}},
) where {Style} = Style()

# recursively unwrap axes broadcast arguments in a way that is statically reducible by the optimizer
axes_args(args::Tuple) = unrolled_tuple_map(axes, args)

@inline instantiate_args(args::Tuple) =
    unrolled_tuple_map(Base.Broadcast.instantiate, args)

function Base.axes(opbc::OperatorBroadcasted)
    if isnothing(opbc.axes)
        return_space(opbc.op, axes_args(opbc.args)...)
    else
        opbc.axes
    end
end
Base.Broadcast.broadcastable(opbc::OperatorBroadcasted) = opbc
Base.copy(opbc::OperatorBroadcasted) = copyto!(similar(opbc), opbc)
Base.similar(opbc::OperatorBroadcasted, ::Type{Eltype}) where {Eltype} =
    Field(Eltype, axes(opbc))

# Define similar to match DataStyle and AbstractFieldStyle broadcasting
Base.similar(opbc::OperatorBroadcasted) =
    similar(opbc, drop_auto_broadcasters(eltype(opbc)))

function Base.Broadcast.materialize(opbc::OperatorBroadcasted)
    copy(Base.Broadcast.instantiate(opbc))
end

function Base.Broadcast.materialize!(dest, opbc::OperatorBroadcasted)
    copyto!(dest, Base.Broadcast.instantiate(opbc))
end


# when sending Broadcasted objects to the GPU, we strip out the space
# information at each level of the broadcast tree and Fields, replacing with
# PlaceholderSpace. this reduces the amount runtime parameter data we send to
# the GPU, which is quite limited (~4kB).

# Functions for CUDASpectralStyle
struct PlaceholderSpace <: Spaces.AbstractSpace end
struct LevelPlaceholderSpace <: Spaces.AbstractSpace end
struct CenterPlaceholderSpace <: Spaces.AbstractSpace end
struct FacePlaceholderSpace <: Spaces.AbstractSpace end

for op in (:level, :slab, :column)
    @eval $op(space::PlaceholderSpace, indices...) = space
    @eval $op(space::LevelPlaceholderSpace, indices...) = space
    @eval $op(space::CenterPlaceholderSpace, indices...) = space
    @eval $op(space::FacePlaceholderSpace, indices...) = space
end

# A LevelPlaceholderSpace stands to PlaceholderSpace as a horizontal space
# stands to its extruded space; a sliced pointwise node mixing level fields
# with fields on the enclosing space reaches broadcast_shape with both, and
# without this relation it throws (in a GPU kernel, with no stacktrace).
Spaces.issubspace(::LevelPlaceholderSpace, ::PlaceholderSpace) = true

placeholder_space(current_space, parent_space) = current_space
placeholder_space(current_space::T, parent_space::T) where {T} =
    PlaceholderSpace()
placeholder_space(
    current_space::Spaces.AbstractPointSpace,
    parent_space::Spaces.AbstractFiniteDifferenceSpace,
) = LevelPlaceholderSpace()
placeholder_space(
    current_space::Spaces.AbstractSpectralElementSpace,
    parent_space::Spaces.ExtrudedFiniteDifferenceSpace,
) = LevelPlaceholderSpace()
placeholder_space(
    current_space::Spaces.CenterFiniteDifferenceSpace,
    parent_space::Spaces.FaceFiniteDifferenceSpace,
) = CenterPlaceholderSpace()
placeholder_space(
    current_space::Spaces.CenterExtrudedFiniteDifferenceSpace,
    parent_space::Spaces.FaceExtrudedFiniteDifferenceSpace,
) = CenterPlaceholderSpace()
placeholder_space(
    current_space::Spaces.CenterMultiColumnFiniteDifferenceSpace,
    parent_space::Spaces.FaceMultiColumnFiniteDifferenceSpace,
) = CenterPlaceholderSpace()
placeholder_space(
    current_space::Spaces.FaceFiniteDifferenceSpace,
    parent_space::Spaces.CenterFiniteDifferenceSpace,
) = FacePlaceholderSpace()
placeholder_space(
    current_space::Spaces.FaceExtrudedFiniteDifferenceSpace,
    parent_space::Spaces.CenterExtrudedFiniteDifferenceSpace,
) = FacePlaceholderSpace()
placeholder_space(
    current_space::Spaces.FaceMultiColumnFiniteDifferenceSpace,
    parent_space::Spaces.CenterMultiColumnFiniteDifferenceSpace,
) = FacePlaceholderSpace()

@inline reconstruct_placeholder_space(current_space, parent_space) =
    current_space
@inline reconstruct_placeholder_space(::PlaceholderSpace, parent_space) =
    parent_space
@inline reconstruct_placeholder_space(::LevelPlaceholderSpace, parent_space) =
    Spaces.level(parent_space, left_idx(parent_space)) # extract arbitrary level
@inline reconstruct_placeholder_space(
    ::CenterPlaceholderSpace,
    parent_space::Spaces.FaceFiniteDifferenceSpace,
) = Spaces.CenterFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::CenterPlaceholderSpace,
    parent_space::Spaces.FaceExtrudedFiniteDifferenceSpace,
) = Spaces.CenterExtrudedFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::FacePlaceholderSpace,
    parent_space::Spaces.CenterFiniteDifferenceSpace,
) = Spaces.FaceFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::FacePlaceholderSpace,
    parent_space::Spaces.CenterExtrudedFiniteDifferenceSpace,
) = Spaces.FaceExtrudedFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::FacePlaceholderSpace,
    parent_space::Union{
        Spaces.FaceFiniteDifferenceSpace,
        Spaces.FaceExtrudedFiniteDifferenceSpace,
    },
) = parent_space
@inline reconstruct_placeholder_space(
    ::CenterPlaceholderSpace,
    parent_space::Union{
        Spaces.CenterFiniteDifferenceSpace,
        Spaces.CenterExtrudedFiniteDifferenceSpace,
    },
) = parent_space

@inline reconstruct_placeholder_space(
    ::CenterPlaceholderSpace,
    parent_space::Spaces.FaceMultiColumnFiniteDifferenceSpace,
) = Spaces.CenterMultiColumnFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::FacePlaceholderSpace,
    parent_space::Spaces.CenterMultiColumnFiniteDifferenceSpace,
) = Spaces.FaceMultiColumnFiniteDifferenceSpace(parent_space)
@inline reconstruct_placeholder_space(
    ::FacePlaceholderSpace,
    parent_space::Spaces.FaceMultiColumnFiniteDifferenceSpace,
) = parent_space
@inline reconstruct_placeholder_space(
    ::CenterPlaceholderSpace,
    parent_space::Spaces.CenterMultiColumnFiniteDifferenceSpace,
) = parent_space

strip_space(arg, parent_space) = arg
function strip_space(field::Field, parent_space)
    space = placeholder_space(axes(field), parent_space)
    return Field(Fields.field_values(field), space)
end
function strip_space(bc::Broadcast.Broadcasted, parent_space)
    # Strip each node's args relative to the node's own space, not the space
    # passed in from above: device-side reconstruction resolves each stripped
    # space against the directly enclosing node's space, so stripping against a
    # farther ancestor would reconstruct to the wrong space.
    current_space = axes(bc)
    args = unrolled_tuple_map(Base.Fix2(strip_space, current_space), bc.args)
    space = placeholder_space(current_space, parent_space)
    return Broadcast.Broadcasted(bc.style, bc.f, args, space)
end

unstrip_space(arg, parent_space) = arg
function unstrip_space(field::Field, parent_space)
    space = reconstruct_placeholder_space(axes(field), parent_space)
    return Field(Fields.field_values(field), space)
end
function unstrip_space(bc::Broadcast.Broadcasted, parent_space)
    # Invert strip_space: reconstruct this node's space against the enclosing
    # node's space, and then reconstruct the args against this node's space.
    space = reconstruct_placeholder_space(axes(bc), parent_space)
    args = unrolled_tuple_map(Base.Fix2(unstrip_space, space), bc.args)
    return Broadcast.Broadcasted(bc.style, bc.f, args, space)
end
