module Operators

import LinearAlgebra, Adapt

using StaticArrays

import Base.Broadcast: Broadcasted

import ..level, ..slab, ..column
import ClimaComms
import ..Utilities: Cache, new, unwrap, is_auto_broadcastable
import ..Utilities: add_auto_broadcasters, drop_auto_broadcasters
import ..Utilities: @drop_recursion_limits, @drop_constprop
import ..DebugOnly: call_post_op_callback, post_op_callback
import ..DataLayouts
import ..Geometry: Geometry, ⊗
import ..Spaces: Spaces, Quadratures, AbstractSpace
import ..Topologies
import ..Meshes
import ..Grids
import ..Fields: Fields, Field, MaybeLazyField
import UnrolledUtilities: unrolled_foreach, unrolled_map, unrolled_any, unrolled_all
import UnrolledUtilities: unrolled_filter, unrolled_in, unrolled_sum, unrolled_maximum
import LazyBroadcast: lazy
import ..Utilities.Unrolled: unrolled_tuple_map

"""
    AbstractOperator

Supertype for ClimaCore operators. An operator is a pseudo-function: it can't be
called directly, but can be broadcasted over `Field`s.
"""
abstract type AbstractOperator end

"""
    AbstractBoundaryCondition

Supertype for the boundary conditions of finite difference and discontinuous
Galerkin operators ([`VerticalBoundaryCondition`](@ref) and
[`HorizontalBoundaryCondition`](@ref), respectively).
"""
abstract type AbstractBoundaryCondition end

@generated invalid_boundary_condition_error(op, bc) =
    :(error($("Boundary `$bc` is not supported for operator `$op`")))

"""
    return_eltype(op, args...)

Element type of the `Field` generated by applying an [`AbstractOperator`](@ref)
to the given `args`.
"""
function return_eltype end

"""
    return_space(op, args...)

Axes of the `Field` generated by applying an [`AbstractOperator`](@ref) to the
given `args`.
"""
function return_space end

"""
    apply_operator(op, args...)

Materialize the `Field` generated by applying an [`AbstractOperator`](@ref) to
the given `args`.

# Buffer reuse invariant

On GPUs, buffers of equal byte size can be assigned to the same shared memory
(see [`DataLayouts.scoped_static_array`](@ref)), so each `apply_operator` method
keeps at most one buffer of each size live at a time, separating every reuse
from the previous use with a [`DataLayouts.synchronize`](@ref). The destination
stays live for the whole application and may alias another live application's
destination (as in `@. wdiv(grad(a)) + wdiv(grad(b))`), so it lives in
thread-local registers (see [`register_similar`](@ref)). This also applies to
buffers materialized inside a fused slice loop ([`materialize_buffer`](@ref)
moves register data into shared memory when it is owned by multiple threads).

Several operators rely on their allocation sites compiling into one function
(equal-size globals merge only across separately compiled functions), which is
verified by the `test/Operators/spectralelement/gpu_rectilinear.jl` unit tests:
 - [`SplitDivergence`](@ref) has a buffered argument with the same size as the
   output of `materialize_contravariant`,
 - [`Interpolate`](@ref) and [`Restrict`](@ref) both have a buffered argument
   with the same size as the output of `sequential_muladd_slab!` when
   interpolating/restricting to a space with an equal or lower quadrature order.
"""
function apply_operator end

include("broadcast.jl")
include("spectralelement.jl")
include("numericalflux.jl")
include("dg_fluxes.jl")
include("completion.jl")
include("tensordivergence.jl")
include("laplacians.jl")
include("finitedifference.jl")
include("remapping.jl")
include("integrals.jl")
include("deprecated.jl")

end # module
