module Operators

import LinearAlgebra, Adapt

using StaticArrays, UnrolledUtilities

import Base.Broadcast: Broadcasted

import ..level, ..slab, ..column
import ClimaComms
import ..Utilities:
    Cache,
    new,
    unwrap,
    is_auto_broadcastable,
    add_auto_broadcasters,
    drop_auto_broadcasters
import ..Utilities
import ..Utilities: @drop_recursion_limits, @drop_constprop
import ..DebugOnly: call_post_op_callback, post_op_callback
import ..DataLayouts
import ..Geometry: Geometry, ⊗
import ..Spaces: Spaces, Quadratures, AbstractSpace
import ..Topologies
import ..Meshes
import ..Grids
import ..Fields: Fields, Field, LazyField, MaybeLazyField
import LazyBroadcast: lazy

"""
    AbstractOperator

Supertype for ClimaCore operators. An operator is a pseudo-function: it cannot be
called directly, but can be broadcasted over `Field`s. Subtypes are
[`FiniteDifferenceOperator`](@ref) and [`SpectralElementOperator`](@ref).
"""
abstract type AbstractOperator end

"""
    AbstractBoundaryCondition

Supertype for the boundary conditions of both the finite-difference and the
discontinuous-Galerkin operators. The two families act on different mesh
directions, so every boundary condition is either a
[`VerticalBoundaryCondition`](@ref) or a
[`HorizontalBoundaryCondition`](@ref), never both.
"""
abstract type AbstractBoundaryCondition end

"""
    promote_bcs(op::AbstractOperator, FT)

Promote the boundary conditions of `op`, so that integer-valued boundary
conditions take the space's float type `FT`.
"""
promote_bcs(op::AbstractOperator, ::Type{FT}) where {FT} = op

"""
    return_eltype(op, args...)

Return the element type of the `Field` generated by an [`AbstractOperator`](@ref)
when applied to the given `args`.
"""
function return_eltype end

"""
    return_space(op, args...)

Return the space (axes) of the `Field` generated by an [`AbstractOperator`](@ref)
when applied to the given `args`.
"""
function return_space end

"""
    apply_operator(op, args...)

Eagerly evaluate the [`SpectralElementOperator`](@ref) `op` over one slab of
slab `Field`s and/or lazy pointwise broadcasts over slabs, or the
[`FiniteDifferenceOperator`](@ref) `op` over one column of column `Field`s
and/or lazy broadcasts over columns.

# Notes

**Buffer reuse invariant.** On GPUs, buffers of equal byte size can be assigned to the same shared memory
(see `DataLayouts.scoped_static_array`), so each `apply_operator` method keeps
at most one buffer of each size live at a time, separating every reuse from the
previous use with a `DataLayouts.synchronize`. A finite difference operator
caches every argument that it reads at neighboring points (see
[`cached_arg`](@ref)), and an operator with cached arguments is applied before
any expression that contains it is cached or evaluated, so only the cached
arguments of one application are ever live at the same time. Every operator in
ClimaCore caches at most one argument, except for `FCTZalesak`, whose two cached
arguments lie on different staggerings, so their buffers can only have equal byte
sizes on columns with very few levels. The destination stays live for
the whole application and may alias a *different* live application's destination
(as in `@. wdiv(grad(a)) + wdiv(grad(b))`), so it lives in per-thread registers
([`register_similar`](@ref)), as do temporaries materialized inside a fused
slice loop; [`materialize_buffer`](@ref) republishes register-resident values
whenever an operator must read them across threads. Two configurations rely on
their allocation sites compiling into one unit (equal-size globals merge only
across separately compiled functions): interpolation to an equal or lower
degree gives a buffered argument and `sequential_muladd_slab!`'s partial result
the same byte size, and `SplitDivergence`'s buffered second argument stays live
across its equal-size per-dimension intermediates. Both are pinned by GPU value
tests in `test/Operators/spectralelement/gpu_rectilinear.jl`.
"""
function apply_operator end

include("broadcast.jl")
include("spectralelement.jl")
include("numericalflux.jl")
include("dg_fluxes.jl")
include("completion.jl")
include("tensordivergence.jl")
include("laplacians.jl")
include("finitedifference.jl")
include("remapping.jl")
include("integrals.jl")

end # module
