status = [
  "test-os (ubuntu-latest)",
  "test-os (windows-latest)",
  "test-os (macos-latest)",
  "buildkite/climatemachinecore-ci",
  "format"
]
delete_merged_branches = true
timeout_sec = 12600
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
