status = [
  "test-os 1.4 - (ubuntu-latest)",
  "test-os 1.4 - (windows-latest)",
  "test-os 1.4 - (macos-latest)",
  "test-os 1.5 - (ubuntu-latest)",
  "test-os 1.5 - (windows-latest)",
  "test-os 1.5 - (macos-latest)",
  "test-os 1.6 - (ubuntu-latest)",
  "test-os 1.6 - (windows-latest)",
  "test-os 1.6 - (macos-latest)",
  "buildkite/climatemachinecore-ci",
  "format",
  "docbuild"
]
delete_merged_branches = true
timeout_sec = 12600
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
