[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[preferences.CUDA_Runtime_jll]
version = "12.2"
local = "true"

[preferences.MPIPreferences]
_format = "1.0"
binary = "MPItrampoline_jll"
