env:
  JULIA_VERSION: "1.6.2"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=examples/column -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples/column -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=examples/bickleyjet -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples/bickleyjet -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=examples/hybrid -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples/hybrid -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=examples/sphere -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples/sphere -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=benchmarks/bickleyjet -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=benchmarks/bickleyjet -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "init :flower_playing_cards:"
    key: "init_gpu_env"
    command:
      - "export CUDA_HOME=/usr/local/cuda-$$CUDA_VERSION"

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile(;strict=true)'"

      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"

      - "julia --project=benchmarks/bickleyjet -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=benchmarks/bickleyjet -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --color=yes --check-bounds=yes --project=test test/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":flower_playing_cards: unit tests"
    key: "gpu_unittests"
    command:
      - "export CUDA_HOME=/usr/local/cuda-$$CUDA_VERSION"
      - "julia --color=yes --check-bounds=yes --project=test test/runtests.jl CUDA"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - label: ":computer: Column Heat Diffusion Eq"
    key: "cpu_column_heat"
    command:
      - "julia --color=yes --project=examples/column examples/column/heat.jl"
    artifact_paths:
      - "examples/column/output/heat/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Advection Step Eq"
    key: "cpu_column_step_advect"
    command:
      - "julia --color=yes --project=examples/column examples/column/step.jl"
    artifact_paths:
      - "examples/column/output/advect_step_function/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Advection Eq"
    key: "cpu_column_advect"
    command:
      - "julia --color=yes --project=examples/column examples/column/advect.jl"
    artifact_paths:
      - "examples/column/output/advect/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Advection Diffusion Eq"
    key: "cpu_column_advect_diff"
    command:
      - "julia --color=yes --project=examples/column examples/column/advect_diffusion.jl"
    artifact_paths:
      - "examples/column/output/advect_diffusion/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Ekman Eq"
    key: "cpu_column_ekman"
    command:
      - "julia --color=yes --project=examples/column examples/column/ekman.jl"
    artifact_paths:
      - "examples/column/output/ekman/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Hydrostatic Ekman Eq"
    key: "cpu_column_hydrostatic_ekman"
    command:
      - "julia --color=yes --project=examples/column examples/column/hydrostatic_ekman.jl"
    artifact_paths:
      - "examples/column/output/hydrostatic_ekman/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Wave Eq"
    key: "cpu_column_wave"
    command:
      - "julia --color=yes --project=examples/column examples/column/wave.jl"
    artifact_paths:
      - "examples/column/output/wave/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Hydrostatic Balance Eq"
    key: "cpu_column_hydrostatic"
    command:
      - "julia --color=yes --project=examples/column examples/column/hydrostatic.jl"
    artifact_paths:
      - "examples/column/output/hydrostatic/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Column Hydrostatic Balance Eq - implicit"
    key: "cpu_column_hydrostatic_implicit"
    command:
      - "julia --color=yes --project=examples/column examples/column/hydrostatic_implicit.jl"
    artifact_paths:
      - "examples/column/output/hydrostatic_implicit/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet CG"
    key: "cpu_bickleyjet_cg"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_cg.jl"
    artifact_paths:
      - "examples/bickleyjet/output/cg/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet CG unstructured mesh"
    key: "cpu_bickleyjet_cg_unsmesh"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_cg_unsmesh.jl"
    artifact_paths:
      - "examples/bickleyjet/output/cg_unsmesh/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet CG vector invariant hyperviscosity"
    key: "cpu_bickleyjet_cg_invariant_hypervisc"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_cg_invariant_hypervisc.jl"
    artifact_paths:
      - "examples/bickleyjet/output/cg_invariant_hypervisc/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet DG rusanov"
    key: "cpu_bickleyjet_dg_rusanov"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_dg.jl rusanov"
    artifact_paths:
      - "examples/bickleyjet/output/dg_rusanov/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet DG roe"
    key: "cpu_bickleyjet_dg_roe"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_dg.jl roe"
    artifact_paths:
      - "examples/bickleyjet/output/dg_roe/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Bickley jet DG roe noslip"
    key: "cpu_bickleyjet_dg_roe_noslip"
    command:
      - "julia --color=yes --project=examples/bickleyjet examples/bickleyjet/bickleyjet_dg.jl roe noslip"
    artifact_paths:
      - "examples/bickleyjet/output/dg_roe_noslip/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Rising Bubble hybrid"
    key: "cpu_rising_bubble_hybrid"
    command:
      - "julia --color=yes --project=examples/hybrid examples/hybrid/bubble.jl"
    artifact_paths:
      - "examples/hybrid/output/bubble/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Solid body CG sphere cosine bell alpha0"
    key: "cpu_solidbody_cg_sphere_cosine_bell_alpha0"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/solidbody.jl"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_solidbody_cosine_bell_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Solid body CG sphere cosine bell alpha45"
    key: "cpu_solidbody_cg_sphere_cosine_bell_alpha45"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/solidbody.jl cosine_bell alpha45"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_solidbody_cosine_bell_alpha45/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Solid body CG sphere gaussian bell alpha0"
    key: "cpu_solidbody_cg_sphere_gaussian_bell_alpha0"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/solidbody.jl gaussian_bell"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_solidbody_gaussian_bell_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Solid body CG sphere gaussian bell alpha45"
    key: "cpu_solidbody_cg_sphere_gaussian_bell_alpha45"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/solidbody.jl gaussian_bell alpha45"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_solidbody_gaussian_bell_alpha45/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Steady-state shallow water 2D CG sphere alpha0"
    key: "cpu_shallowwater_2d_cg_sphere_alpha0"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_steady_state_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Steady-state shallow water 2D CG sphere alpha45"
    key: "cpu_shallowwater_2d_cg_sphere_alpha45"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl steady_state alpha45"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_steady_state_alpha45/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Steady-state shallow water 2D CG sphere with compact support alpha0"
    key: "cpu_shallowwater_2d_cg_sphere_compact_alpha0"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl steady_state_compact"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_steady_state_compact_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Steady-state shallow water 2D CG sphere with compact support alpha60"
    key: "cpu_shallowwater_2d_cg_sphere_compact_alpha60"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl steady_state_compact alpha60"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_steady_state_compact_alpha60/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Shallow water 2D CG sphere barotropic instability alpha0"
    key: "cpu_shallowwater_2d_cg_sphere_barotropic_alpha0"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl barotropic_instability"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_barotropic_instability_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Shallow water 2D CG sphere barotropic instability alpha30"
    key: "cpu_shallowwater_2d_cg_sphere_barotropic_alpha30"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl barotropic_instability alpha30"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_barotropic_instability_alpha30/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Non-uniform shallow water 2D CG sphere alpha0"
    key: "cpu_nonuniform_shallowwater_2d_cg_sphere"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl mountain"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_mountain_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":computer: Rossby Haurwitz 2D CG sphere"
    key: "cpu_rossbyhaurwitz_2d_cg_sphere"
    command:
      - "julia --color=yes --project=examples/sphere examples/sphere/shallow_water.jl rossby_haurwitz"
    artifact_paths:
      - "examples/sphere/output/cg_sphere_shallowwater_rossby_haurwitz_alpha0/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: ":flower_playing_cards: Bickley jet DG"
    key: "benchmark_bickleyjet_dg"
    command:
      - "julia --color=yes --project=benchmarks/bickleyjet benchmarks/bickleyjet/core_vs_ref.jl"
    artifact_paths:
      - "benchmarks/bickleyjet/*.png"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - label: ":computer: :fast_forward: Bickley jet DG reference thread scaling"
    key: "cpu_benchmark_bickleyjet_dg_thread_scaling"
    command:
      - "julia --color=yes --project=benchmarks/bickleyjet benchmarks/bickleyjet/ref_thread_scaling.jl"
    artifact_paths:
      - "benchmarks/bickleyjet/*.png"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
      slurm_cpus_per_task: 16
      slurm_exclusive: ""
