agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_10_08

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_CPU_TARGET: 'broadwell;skylake'
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "init_cpu_env"
    command:
      - |
        if [ -n "$$CLEAR_DEPOT" ]; then
          echo "--- Clearing depot"
          rm -rf ${JULIA_DEPOT_PATH}
        fi

      - echo "--- Instantiate buildkite env"
      - "julia --project=.buildkite --check-bounds=yes -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      - "julia --project=.buildkite -e 'using CUDA; CUDA.precompile_runtime()'"

      - echo "--- Instantiate lib/ClimaCoreTempestRemap"
      - "julia --project=lib/ClimaCoreTempestRemap -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate benchmarks"
      - "julia --project=benchmarks/bickleyjet -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

    agents:
      slurm_mem: 80G
      slurm_gpus: 1
      slurm_cpus_per_task: 12
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12

  - wait

  - group: "Unit: Package-wide"
    steps:

      - label: "Unit: aqua"
        key: unit_aqua
        command: "julia --color=yes --check-bounds=yes --project=.buildkite test/aqua.jl"

      - label: "Unit: cuda"
        key: unit_cuda_functional
        command:
          - "julia --project=.buildkite -e 'using CUDA; CUDA.versioninfo()'"
          - "julia --color=yes --check-bounds=yes --project=.buildkite test/gpu/cuda.jl CUDA"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1

  - group: "Unit: MatrixFields"
    steps:

      - label: "Unit: field matrix solvers (CPU)"
        key: unit_field_matrix_solvers_cpu
        command: "julia --color=yes --check-bounds=yes --project=.buildkite test/MatrixFields/field_matrix_solvers.jl"
        agents:
          slurm_mem: 40GB

      - label: "Unit: field matrix solvers (GPU)"
        key: unit_field_matrix_solvers_gpu
        command: "julia --color=yes --project=.buildkite test/MatrixFields/field_matrix_solvers.jl"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
          slurm_mem: 40GB

  - group: "Analysis"
    steps:

      - label: "Analysis: Flamegraph profile"
        key: "cpu_flamegraph"
        command: "julia --color=yes --project=.buildkite perf/flame.jl"
        artifact_paths:
          - "perf/output/*"

  - wait

  - label: ":chart_with_downwards_trend: build history"
    command:
      - "build_history staging"
    artifact_paths:
      - "build_history.html"
