agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_10_08

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1

steps:

  - label: "CUDA 5.5"
    key: "init27"
    command:
      - echo "--- Instantiate buildkite env"
      - rm -rf $JULIA_DEPOT_PATH
      - "julia --project=.buildkite --check-bounds=yes -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      - "julia --project=.buildkite -e 'using CUDA; CUDA.precompile_runtime()'"
    agents:
      slurm_mem: 80G
      slurm_gpus: 1
      slurm_cpus_per_task: 12
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12

  - wait

  - label: "Unit: distributed remapping with CUDA (2 processes)"
    key: distributed_remapping_gpu_2procs27
    command: "srun julia --color=yes --check-bounds=yes --project=.buildkite test/Remapping/distributed_remapping.jl"
    soft_fail: true
    env:
      CLIMACOMMS_CONTEXT: "MPI"
      CLIMACOMMS_DEVICE: "CUDA"
    agents:
      slurm_ntasks: 2
      slurm_gpus_per_task: 1


  - wait

  - label: "CUDA 5.6"
    key: "init11"
    command:
      - echo "--- Instantiate buildkite env"
      - "julia --project=.buildkite --check-bounds=yes -e 'using Pkg;Pkg.add(name=\"CUDA\", version=\"5.6.1\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      - "julia --project=.buildkite -e 'using CUDA; CUDA.precompile_runtime()'"
    agents:
      slurm_mem: 80G
      slurm_gpus: 1
      slurm_cpus_per_task: 12
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12

  - wait

  - label: "Unit: distributed remapping with CUDA (2 processes)"
    key: distributed_remapping_gpu_2procs
    command: "srun julia --color=yes --check-bounds=yes --project=.buildkite test/Remapping/distributed_remapping.jl"
    soft_fail: true
    timeout_in_minutes: 5
    env:
      CLIMACOMMS_CONTEXT: "MPI"
      CLIMACOMMS_DEVICE: "CUDA"
    agents:
      slurm_ntasks: 2
      slurm_gpus_per_task: 1
