env:
  JULIA_VERSION: "1.7.1"
  MPICH_VERSION: "4.0.0"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.3"
  OPENBLAS_NUM_THREADS: 1
  PROFILE_PATH: "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo --- Instantiate scaling test"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "echo --- Instantiate status"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (1) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_1p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_1_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.1.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 1
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 1

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (2) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_2p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_2_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.2.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 2
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 2

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (4) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_4p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_4_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.4.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 4
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 4

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (8) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_8p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_8_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.8.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 8
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 8

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (16) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_16p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_16_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.16.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 16
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 16

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (32) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_32p"
    command:
      - "module load cuda/11.3 nsight-systems/2022.2.1"
      - "nsys profile --trace=nvtx,mpi --mpi-impl=mpich --output=$$PROFILE_PATH/report.%q{NPROCS} mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_32_processes.jld2"
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/report.32.*"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
      NPROCS: 32
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 32

  - label: ":computer: MPI Held-Suarez scaling test(ρθ) - (64) processes"
    key: "cpu_mpi_held_suarez_scaling_test_rhotheta_64p"
    command:
      - "mpiexec julia --color=yes --project=examples examples/hybrid/driver.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/scaling_data_64_processes.jld2"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
      CLIMACORE_DISTRIBUTED: "MPI"
    agents:
      config: cpu
      queue: central
      slurm_nodes: 2
      slurm_tasks_per_node: 32

  - wait

  - label: ":computer: scaling plots"
    key: "cpu_scaling_plots"
    command:
      - "julia --color=yes --project=examples examples/hybrid/plot_scaling_results.jl"
    artifact_paths:
      - "examples/hybrid/sphere/output/held_suarez_rhotheta_scaling/Float32/*.png"
    env:
      TEST_NAME: "sphere/held_suarez_rhotheta_scaling"
    agents:
      config: cpu
      queue: central
      slurm_nodes: 1
      slurm_tasks_per_node: 1
