import LinearAlgebra: ldiv!
using ClimaCore: Spaces, Fields, Operators
using ClimaCore.Utilities: half
using ClimaCore.MatrixFields
using ClimaCore.MatrixFields: @name

"""
    ImplicitEquationJacobian(Y, [flags])

The Jacobian `∂R/∂Y` of the implicit residual `R(Y) = Yᵖʳᵉᵛ + δt * γ * Yₜ - Y`.

Here `δt` is the timestep, `γ` a scalar set by the timestepping scheme, `Y` the
current approximation of the implicit stage value, `Yₜ` the value returned by
`implicit_tendency!(Yₜ, Y, p, t)`, and `Yᵖʳᵉᵛ` a linear combination of the
scheme's previous stage values. In terms of the tendency's Jacobian `∂Yₜ/∂Y`,
the residual's is `δt * γ * ∂Yₜ/∂Y - I`.

`ClimaTimeSteppers` uses this to solve `∂R/∂Y * δY = R`, the linear system that
lets Newton's method iterate toward the root of `R(Y) = 0`. That solve is a call
to `ldiv!(δY, ∂R/∂Y, R)`; `δY` and `R` are `FieldVector`s, or — when a Krylov
method is used — arbitrary `AbstractVector`s, which are converted internally.

`implicit_equation_jacobian!` sets `∂R/∂Y` from `Y` and `δt * γ`. Optional
`flags` passed here are available to it.
"""
struct ImplicitEquationJacobian{TJ, RJ, F, V}
    ∂Yₜ∂Y::TJ # nonzero blocks of the implicit tendency's Jacobian
    ∂R∂Y::RJ # the full implicit residual's Jacobian, and its linear solver
    flags::F # flags for computing the implicit tendency's Jacobian
    R_field_vector::V # cache that is used to evaluate ldiv! for Krylov methods
    δY_field_vector::V # cache that is used to evaluate ldiv! for Krylov methods
end

function ImplicitEquationJacobian(Y, flags = (;))
    FT = eltype(Y)

    ᶜρ_name = @name(c.ρ)
    ᶜ𝔼_name = @name(c.ρe)
    ᶠ𝕄_name = @name(f.w)

    BidiagonalRow_C3 = BidiagonalMatrixRow{C3{FT}}
    BidiagonalRow_ACT3 = BidiagonalMatrixRow{typeof(CT3(FT(0))')}
    QuaddiagonalRow_ACT3 = QuaddiagonalMatrixRow{typeof(CT3(FT(0))')}
    TridiagonalRow_C3xACT3 =
        TridiagonalMatrixRow{typeof(C3(FT(0)) * CT3(FT(0))')}
    ∂ᶜ𝔼ₜ∂ᶠ𝕄_Row_ACT3 =
        flags.∂ᶜ𝔼ₜ∂ᶠ𝕄_mode == :exact && :ρe in propertynames(Y.c) ?
        QuaddiagonalRow_ACT3 : BidiagonalRow_ACT3
    ∂Yₜ∂Y = MatrixFields.FieldMatrix(
        (ᶜρ_name, ᶠ𝕄_name) => zeros(BidiagonalRow_ACT3, axes(Y.c)),
        (ᶜ𝔼_name, ᶠ𝕄_name) => zeros(∂ᶜ𝔼ₜ∂ᶠ𝕄_Row_ACT3, axes(Y.c)),
        (ᶠ𝕄_name, ᶜρ_name) => zeros(BidiagonalRow_C3, axes(Y.f)),
        (ᶠ𝕄_name, ᶜ𝔼_name) => zeros(BidiagonalRow_C3, axes(Y.f)),
        (ᶠ𝕄_name, ᶠ𝕄_name) => zeros(TridiagonalRow_C3xACT3, axes(Y.f)),
    )

    # When ∂Yₜ∂Y is sparse, one(∂Yₜ∂Y) doesn't contain every diagonal block.
    # To ensure that ∂R∂Y is invertible, we need to call identity_field_matrix.
    I = MatrixFields.identity_field_matrix(Y)

    δtγ = FT(1)
    ∂R∂Y = δtγ .* ∂Yₜ∂Y .- I
    alg = MatrixFields.BlockArrowheadSolve(ᶜρ_name, ᶜ𝔼_name)

    return ImplicitEquationJacobian(
        ∂Yₜ∂Y,
        FieldMatrixWithSolver(∂R∂Y, Y, alg),
        flags,
        similar(Y),
        similar(Y),
    )
end

# Required for compatibility with ClimaTimeSteppers.jl
Base.similar(j::ImplicitEquationJacobian) = ImplicitEquationJacobian(
    similar(j.∂Yₜ∂Y),
    similar(j.∂R∂Y),
    j.flags,
    j.R_field_vector,
    j.δY_field_vector,
)

# Required for compatibility with ClimaTimeSteppers.jl
Base.zero(j::ImplicitEquationJacobian) = ImplicitEquationJacobian(
    zero(j.∂Yₜ∂Y),
    zero(j.∂R∂Y),
    j.flags,
    j.R_field_vector,
    j.δY_field_vector,
)

# This method for ldiv! is called by Newton's method from ClimaTimeSteppers.jl.
# It solves ∂R∂Y * δY = R for δY, where R is the implicit residual.
ldiv!(
    δY::Fields.FieldVector,
    j::ImplicitEquationJacobian,
    R::Fields.FieldVector,
) = ldiv!(δY, j.∂R∂Y, R)

# This method for ldiv! is called by Krylov.jl from ClimaTimeSteppers.jl.
# See https://github.com/JuliaSmoothOptimizers/Krylov.jl/issues/605 for a
# a similar way of handling the AbstractVectors generated by Krylov.jl.
function ldiv!(
    δY::AbstractVector,
    j::ImplicitEquationJacobian,
    R::AbstractVector,
)
    j.R_field_vector .= R
    ldiv!(j.δY_field_vector, j, j.R_field_vector)
    δY .= j.δY_field_vector
end
