#! format: off

function func_arg_types(FT, ::typeof(Geometry.project))
    return [
    (ContravariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, Contravariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Contravariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Contravariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Contravariant3Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, WVector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, Contravariant3Vector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (ContravariantAxis{(3,)}, WVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant1Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, WVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, UVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, Covariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, Covariant1Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, Contravariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(3,)}, Contravariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, UVVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, UVVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, UVVector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, UVVector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1,)}, Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(2,)}, Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    # 2-argument method types
    # (CovariantAxis{(1, 2)}, Covariant1Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant12Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant123Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant13Vector{FT}),
    # (CovariantAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, CartesianAxis{(1,)}}, StaticArraysCore.SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 3)}, CartesianAxis{(1,)}}, StaticArraysCore.SMatrix{2, 1, FT, 2},},),
    # (LocalAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2, 3)}, CovariantAxis{(1, 2)}}, StaticArraysCore.SMatrix{3, 2, FT, 6},},),
    # (LocalAxis{(1, 2)}, UVVector{FT}),
    # (ContravariantAxis{(1,)}, Contravariant12Vector{FT}),
    # (ContravariantAxis{(2,)}, Contravariant12Vector{FT}),
    # (CovariantAxis{(1, 2, 3)}, Covariant3Vector{FT}),
    # (ContravariantAxis{(3,)}, Contravariant123Vector{FT}),
    # (CovariantAxis{(3,)}, Covariant3Vector{FT}),
    # (ContravariantAxis{(3,)}, Contravariant3Vector{FT}),
    # (LocalAxis{(3,)}, WVector{FT}),
    # (CovariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{1, 2, FT, 2},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{1, 2, FT, 2},},),
    # (LocalAxis{(3,)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{1, 2, FT, 2},},),
    # (CovariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, StaticArraysCore.SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, LocalAxis{(3,)}}, StaticArraysCore.SMatrix{1, 1, FT, 1},},),
    # (LocalAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{2, 2, FT, 4},},),
    # (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{2, 2, FT, 4},},),
    # (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{2, 2, FT, 4},},),
    # (CovariantAxis{(1, 2, 3)}, Covariant123Vector{FT}),
    # (ContravariantAxis{(1,)}, Contravariant123Vector{FT}),
    # (ContravariantAxis{(2,)}, Contravariant123Vector{FT}),
    # (CovariantAxis{(1, 2, 3)}, Covariant12Vector{FT}),
    # (CovariantAxis{(1, 3)}, Covariant1Vector{FT}),
    # (ContravariantAxis{(1,)}, Contravariant13Vector{FT}),
    # (CovariantAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 3)}, LocalAxis{(1,)}}, SMatrix{2, 1, FT, 2},},),
    # (CovariantAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 3)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2},},),
    # (LocalAxis{(1, 3)}, WVector{FT}),
    # (ContravariantAxis{(3,)}, Contravariant13Vector{FT}),
    # (LocalAxis{(1, 3)}, UVector{FT}),
    # (LocalAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 3)}, LocalAxis{(1,)}}, SMatrix{2, 1, FT, 2},},),
    # (LocalAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1},},),
    # (LocalAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 3)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2},},),
    # (LocalAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 3)}, Covariant3Vector{FT}),
    # (CovariantAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4},},),
    # (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(1, 2)}}, SMatrix{3, 2, FT, 6},},),
    # (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(1, 2)}}, SMatrix{3, 2, FT, 6},},),
    # (CovariantAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2},},),
    # (ContravariantAxis{(1,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(3,)}}, SMatrix{3, 1, FT, 3},},),
    # (ContravariantAxis{(2,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(3,)}}, SMatrix{3, 1, FT, 3},},),
    # (LocalAxis{(1, 2, 3)}, WVector{FT}),
    # (LocalAxis{(1, 2, 3)}, UVVector{FT}),
    # (LocalAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(1, 2)}}, SMatrix{3, 2, FT, 6},},),
    # (LocalAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4},},),
    # (LocalAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (ContravariantAxis{(3,)}, AxisTensor{FT, 2, Tuple{ContravariantAxis{(1, 2, 3)}, LocalAxis{(3,)}}, SMatrix{3, 1, FT, 3},},),
    # (LocalAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2},},),
    # (CovariantAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2},},),
    # (CovariantAxis{(1, 2, 3)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 3)}, Covariant13Vector{FT}),
    # (LocalAxis{(3,)}, UWVector{FT}),
    # (LocalAxis{(1,)}, UWVector{FT}),
    ]
end

function func_arg_types(FT, ::typeof(Geometry.transform))
    return [
    # 3-argument method
    (CovariantAxis{(1, 3)}, UWVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1, 3)}, UWVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 3)}, Covariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(1,)}, UWVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1, 3)}, Covariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(1, 2, 3)}, UVWVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1, 2, 3)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2, 3)}, UVWVector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1, 2, 3)}, UVWVector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (LocalAxis{(1, 2, 3)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2)}, UVWVector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (ContravariantAxis{(1, 2, 3)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2, 3)}, Contravariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (LocalAxis{(1, 2, 3)}, Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2)}, Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 2)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(1, 2)}, UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1, 2)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(3,)}, WVector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (CovariantAxis{(3,)}, WVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (LocalAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 3)}, Covariant1Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(1, 2, 3)}, Contravariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (LocalAxis{(1, 2, 3)}, Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2)}, UVWVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (LocalAxis{(3,)}, Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1, 2)}, UVVector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (CovariantAxis{(1, 2)}, Contravariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 2)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1, 2)}, Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 2, 3)}, Contravariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (CovariantAxis{(1,)}, UVector{FT}, LocalGeometry{(1,), XPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (LocalAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (LocalAxis{(1, 2)}, Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (ContravariantAxis{(1, 2)}, UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    # 2-argument method
    # (CovariantAxis{(1, 2)}, Covariant1Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant13Vector{FT}),
    # (CovariantAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, CartesianAxis{(1,)}}, StaticArraysCore.SMatrix{1, 1, FT, 1},},),
    # (CovariantAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 3)}, CartesianAxis{(1,)}}, StaticArraysCore.SMatrix{2, 1, FT, 2},},),
    # (LocalAxis{(1, 2)}, UVVector{FT}),
    # (CovariantAxis{(1, 3)}, Covariant1Vector{FT}),
    # (LocalAxis{(1, 3)}, UWVector{FT}),
    # (CovariantAxis{(1,)}, Covariant13Vector{FT}),
    # (LocalAxis{(1, 3)}, UVector{FT}),
    # (CovariantAxis{(1, 3)}, Covariant13Vector{FT}),
    # (LocalAxis{(1, 3)}, WVector{FT}),
    # (CovariantAxis{(3,)}, Covariant13Vector{FT}),
    # (CovariantAxis{(1, 2, 3)}, Covariant12Vector{FT}),
    # (LocalAxis{(1, 2, 3)}, UVWVector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant123Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant12Vector{FT}),
    # (LocalAxis{(1,)}, UVVector{FT}),
    # (LocalAxis{(1,)}, UVector{FT}),
    # (CovariantAxis{(1,)}, Covariant1Vector{FT}),
    # (LocalAxis{(3,)}, UVVector{FT}),
    # (LocalAxis{(3,)}, WVector{FT}),
    # (CovariantAxis{(3,)}, Covariant3Vector{FT}),
    # (CovariantAxis{(1, 2)}, Covariant3Vector{FT}),
    # (LocalAxis{(1, 2, 3)}, UVVector{FT}),
    # (CovariantAxis{(1, 2, 3)}, Covariant123Vector{FT}),
    # (CovariantAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{2, 2, FT, 4},},),
    # (LocalAxis{(1, 2)}, AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, StaticArraysCore.SMatrix{2, 2, FT, 4},},),
    # (ContravariantAxis{(1, 2)}, Contravariant12Vector{FT}),
    # (CovariantAxis{(1, 2, 3)}, Covariant3Vector{FT}),
    # (ContravariantAxis{(1, 2, 3)}, Contravariant3Vector{FT}),
    # (ContravariantAxis{(1, 2, 3)}, Contravariant123Vector{FT}),
    # (LocalAxis{(1, 2, 3)}, WVector{FT}),
    # (CovariantAxis{(3,)}, Covariant123Vector{FT}),
    # (CovariantAxis{(1, 3)}, Covariant3Vector{FT}),
    # (LocalAxis{(3,)}, UWVector{FT}),
    # (LocalAxis{(3,)}, UVWVector{FT}),
    # (ContravariantAxis{(1, 3)}, Contravariant13Vector{FT}),
    # (ContravariantAxis{(1,)}, Contravariant13Vector{FT}),
    # (ContravariantAxis{(3,)}, Contravariant13Vector{FT}),
    # (LocalAxis{(1,)}, UWVector{FT}),
    # (ContravariantAxis{(1, 2, 3)}, Contravariant12Vector{FT}),
    # (ContravariantAxis{(1, 2)}, Contravariant123Vector{FT}),
    # (ContravariantAxis{(3,)}, Contravariant123Vector{FT}),
    # (LocalAxis{(1, 2)}, UVWVector{FT}),
    # (LocalAxis{(1, 3)}, UVVector{FT}),
    # (ContravariantAxis{(1, 2)}, Contravariant2Vector{FT}),
    # (CovariantAxis{(1, 3)}, Covariant12Vector{FT}),
    # (LocalAxis{(1, 2)}, UWVector{FT}),
    ]
end


function func_arg_types(FT, ::typeof(Geometry.contravariant1))
    return [
    (Covariant123Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant1Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (UVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant13Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (UVVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (UVVector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    ]
end

function func_arg_types(FT, ::typeof(Geometry.contravariant2))
    return [
    (Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant123Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (UVVector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (UVVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(1, 2)}}, SMatrix{2, 2, FT, 4}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(1, 2)}, LocalAxis{(3,)}}, SMatrix{2, 1, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (UVVector{FT}, LocalGeometry{(1, 2), LatLongPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Contravariant12Vector{FT}, LocalGeometry{(1, 2), XYPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    ]
end

function func_arg_types(FT, ::typeof(Geometry.contravariant3))
    return [
    (Covariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Contravariant3Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Contravariant3Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Contravariant123Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant3Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Contravariant3Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant12Vector{FT}, LocalGeometry{(1, 2, 3), LatLongZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (Covariant3Vector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (WVector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (Contravariant3Vector{FT}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(3,), ZPoint{FT}, FT, SMatrix{1, 1, FT, 1}}),
    (WVector{FT}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{ContravariantAxis{(3,)}, CovariantAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (WVector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (Covariant1Vector{FT}, LocalGeometry{(1, 3), XZPoint{FT}, FT, SMatrix{2, 2, FT, 4}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{LocalAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(1, 2)}}, SMatrix{1, 2, FT, 2}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    (AxisTensor{FT, 2, Tuple{CovariantAxis{(3,)}, LocalAxis{(3,)}}, SMatrix{1, 1, FT, 1}}, LocalGeometry{(1, 2, 3), XYZPoint{FT}, FT, SMatrix{3, 3, FT, 9}}),
    ]
end

#! format: on
