#! format: off

function method_info(FT, ::typeof(Geometry.project))
    return [
    (ContravariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(3,)},Contravariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (ContravariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (ContravariantAxis{(3,)},Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (ContravariantAxis{(3,)},Contravariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (ContravariantAxis{(1,)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (ContravariantAxis{(2,)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (ContravariantAxis{(1,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(2,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(3,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (ContravariantAxis{(3,)},Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (ContravariantAxis{(1,)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (ContravariantAxis{(2,)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (ContravariantAxis{(3,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(1,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(2,)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(1,)},UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (ContravariantAxis{(2,)},UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (ContravariantAxis{(1,)},Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (ContravariantAxis{(2,)},Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (ContravariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (ContravariantAxis{(3,)},WVector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (ContravariantAxis{(3,)},Contravariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},0),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},0),
    (ContravariantAxis{(3,)},WVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (ContravariantAxis{(1,)},Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(3,)},WVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,)},UVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(1,)},Covariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (ContravariantAxis{(3,)},Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (ContravariantAxis{(1,)},Contravariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (ContravariantAxis{(3,)},Contravariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (ContravariantAxis{(1,)},UVVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(2,)},UVVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (ContravariantAxis{(1,)},Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (ContravariantAxis{(2,)},Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (ContravariantAxis{(1,)},UVVector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(2,)},UVVector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,)},Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (ContravariantAxis{(2,)},Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    # 2-argument method types
    # (CovariantAxis{(1,2)},Covariant1Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant12Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant123Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant13Vector{FT},0),
    # (CovariantAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},CartesianAxis{(1,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,3)},CartesianAxis{(1,)}},StaticArraysCore.SMatrix{2,1,FT,2},},,0),
    # (LocalAxis{(1,2)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2,3)},CovariantAxis{(1,2)}},StaticArraysCore.SMatrix{3,2,FT,6},},,0),
    # (LocalAxis{(1,2)},UVVector{FT},0),
    # (ContravariantAxis{(1,)},Contravariant12Vector{FT},0),
    # (ContravariantAxis{(2,)},Contravariant12Vector{FT},0),
    # (CovariantAxis{(1,2,3)},Covariant3Vector{FT},0),
    # (ContravariantAxis{(3,)},Contravariant123Vector{FT},0),
    # (CovariantAxis{(3,)},Covariant3Vector{FT},0),
    # (ContravariantAxis{(3,)},Contravariant3Vector{FT},0),
    # (LocalAxis{(3,)},WVector{FT},0),
    # (CovariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (LocalAxis{(3,)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (CovariantAxis{(3,)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},LocalAxis{(3,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (LocalAxis{(1,2)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (CovariantAxis{(1,2,3)},Covariant123Vector{FT},0),
    # (ContravariantAxis{(1,)},Contravariant123Vector{FT},0),
    # (ContravariantAxis{(2,)},Contravariant123Vector{FT},0),
    # (CovariantAxis{(1,2,3)},Covariant12Vector{FT},0),
    # (CovariantAxis{(1,3)},Covariant1Vector{FT},0),
    # (ContravariantAxis{(1,)},Contravariant13Vector{FT},0),
    # (CovariantAxis{(1,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,3)},LocalAxis{(1,)}},SMatrix{2,1,FT,2},},,0),
    # (CovariantAxis{(1,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,3)},LocalAxis{(3,)}},SMatrix{2,1,FT,2},},,0),
    # (LocalAxis{(1,3)},WVector{FT},0),
    # (ContravariantAxis{(3,)},Contravariant13Vector{FT},0),
    # (LocalAxis{(1,3)},UVector{FT},0),
    # (LocalAxis{(1,3)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,3)},LocalAxis{(1,)}},SMatrix{2,1,FT,2},},,0),
    # (LocalAxis{(1,3)},AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1},},,0),
    # (LocalAxis{(1,3)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,3)},LocalAxis{(3,)}},SMatrix{2,1,FT,2},},,0),
    # (LocalAxis{(1,3)},AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,3)},Covariant3Vector{FT},0),
    # (CovariantAxis{(1,2,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4},},,0),
    # (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(1,2)}},SMatrix{3,2,FT,6},},,0),
    # (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(1,2)}},SMatrix{3,2,FT,6},},,0),
    # (CovariantAxis{(1,2,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2},},,0),
    # (ContravariantAxis{(1,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(3,)}},SMatrix{3,1,FT,3},},,0),
    # (ContravariantAxis{(2,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(3,)}},SMatrix{3,1,FT,3},},,0),
    # (LocalAxis{(1,2,3)},WVector{FT},0),
    # (LocalAxis{(1,2,3)},UVVector{FT},0),
    # (LocalAxis{(1,2,3)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(1,2)}},SMatrix{3,2,FT,6},},,0),
    # (LocalAxis{(1,2,3)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4},},,0),
    # (LocalAxis{(1,2,3)},AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (ContravariantAxis{(3,)},AxisTensor{FT,2,Tuple{ContravariantAxis{(1,2,3)},LocalAxis{(3,)}},SMatrix{3,1,FT,3},},,0),
    # (LocalAxis{(1,2,3)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2},},,0),
    # (CovariantAxis{(1,2,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2},},,0),
    # (CovariantAxis{(1,2,3)},AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,3)},Covariant13Vector{FT},0),
    # (LocalAxis{(3,)},UWVector{FT},0),
    # (LocalAxis{(1,)},UWVector{FT},0),
    ]
end

function method_info(FT, ::typeof(Geometry.transform))
    return [
    # 3-argument method
    (CovariantAxis{(1,3)},UWVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,3)},UWVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (LocalAxis{(1,3)},Covariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (CovariantAxis{(1,)},UWVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (CovariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (ContravariantAxis{(1,3)},Covariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (CovariantAxis{(1,2,3)},UVWVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(1,2,3)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},18),
    (CovariantAxis{(1,2,3)},UVWVector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (ContravariantAxis{(1,2,3)},UVWVector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (LocalAxis{(1,2,3)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(1,2)},UVWVector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (ContravariantAxis{(1,2,3)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},18),
    (CovariantAxis{(1,2,3)},Contravariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},18),
    (LocalAxis{(1,2,3)},Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(1,2)},Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (LocalAxis{(1,2)},Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (CovariantAxis{(1,2)},UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,2)},Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (CovariantAxis{(3,)},WVector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (CovariantAxis{(3,)},WVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (LocalAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (LocalAxis{(1,3)},Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (CovariantAxis{(1,2,3)},Contravariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},18),
    (LocalAxis{(1,2,3)},Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(1,2)},UVWVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (LocalAxis{(3,)},Covariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(1,2)},UVVector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (CovariantAxis{(1,2)},Contravariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (LocalAxis{(1,2)},Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,2)},Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (LocalAxis{(1,2,3)},Contravariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (CovariantAxis{(1,)},UVector{FT},FullLocalGeometry{(1,),XPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (LocalAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (LocalAxis{(1,2)},Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (ContravariantAxis{(1,2)},UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    # 2-argument method
    # (CovariantAxis{(1,2)},Covariant1Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant13Vector{FT},0),
    # (CovariantAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},CartesianAxis{(1,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (CovariantAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,3)},CartesianAxis{(1,)}},StaticArraysCore.SMatrix{2,1,FT,2},},,0),
    # (LocalAxis{(1,2)},UVVector{FT},0),
    # (CovariantAxis{(1,3)},Covariant1Vector{FT},0),
    # (LocalAxis{(1,3)},UWVector{FT},0),
    # (CovariantAxis{(1,)},Covariant13Vector{FT},0),
    # (LocalAxis{(1,3)},UVector{FT},0),
    # (CovariantAxis{(1,3)},Covariant13Vector{FT},0),
    # (LocalAxis{(1,3)},WVector{FT},0),
    # (CovariantAxis{(3,)},Covariant13Vector{FT},0),
    # (CovariantAxis{(1,2,3)},Covariant12Vector{FT},0),
    # (LocalAxis{(1,2,3)},UVWVector{FT},0),
    # (CovariantAxis{(1,2)},Covariant123Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant12Vector{FT},0),
    # (LocalAxis{(1,)},UVVector{FT},0),
    # (LocalAxis{(1,)},UVector{FT},0),
    # (CovariantAxis{(1,)},Covariant1Vector{FT},0),
    # (LocalAxis{(3,)},UVVector{FT},0),
    # (LocalAxis{(3,)},WVector{FT},0),
    # (CovariantAxis{(3,)},Covariant3Vector{FT},0),
    # (CovariantAxis{(1,2)},Covariant3Vector{FT},0),
    # (LocalAxis{(1,2,3)},UVVector{FT},0),
    # (CovariantAxis{(1,2,3)},Covariant123Vector{FT},0),
    # (CovariantAxis{(1,2)},AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (LocalAxis{(1,2)},AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (ContravariantAxis{(1,2)},Contravariant12Vector{FT},0),
    # (CovariantAxis{(1,2,3)},Covariant3Vector{FT},0),
    # (ContravariantAxis{(1,2,3)},Contravariant3Vector{FT},0),
    # (ContravariantAxis{(1,2,3)},Contravariant123Vector{FT},0),
    # (LocalAxis{(1,2,3)},WVector{FT},0),
    # (CovariantAxis{(3,)},Covariant123Vector{FT},0),
    # (CovariantAxis{(1,3)},Covariant3Vector{FT},0),
    # (LocalAxis{(3,)},UWVector{FT},0),
    # (LocalAxis{(3,)},UVWVector{FT},0),
    # (ContravariantAxis{(1,3)},Contravariant13Vector{FT},0),
    # (ContravariantAxis{(1,)},Contravariant13Vector{FT},0),
    # (ContravariantAxis{(3,)},Contravariant13Vector{FT},0),
    # (LocalAxis{(1,)},UWVector{FT},0),
    # (ContravariantAxis{(1,2,3)},Contravariant12Vector{FT},0),
    # (ContravariantAxis{(1,2)},Contravariant123Vector{FT},0),
    # (ContravariantAxis{(3,)},Contravariant123Vector{FT},0),
    # (LocalAxis{(1,2)},UVWVector{FT},0),
    # (LocalAxis{(1,3)},UVVector{FT},0),
    # (ContravariantAxis{(1,2)},Contravariant2Vector{FT},0),
    # (CovariantAxis{(1,3)},Covariant12Vector{FT},0),
    # (LocalAxis{(1,2)},UWVector{FT},0),
    ]
end


function method_info(FT, ::typeof(Geometry.contravariant1))
    return [
    (Covariant123Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},6),
    (Covariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (UVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (Covariant13Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (UVVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (UVVector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    ]
end

function method_info(FT, ::typeof(Geometry.contravariant2))
    return [
    (Covariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (Covariant123Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},5),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (UVVector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},8),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (UVVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(1,2)}},SMatrix{2,2,FT,4}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},6),
    (AxisTensor{FT,2,Tuple{LocalAxis{(1,2)},LocalAxis{(3,)}},SMatrix{2,1,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},3),
    (UVVector{FT},FullLocalGeometry{(1,2),LatLongPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (Contravariant12Vector{FT},FullLocalGeometry{(1,2),XYPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    ]
end

function method_info(FT, ::typeof(Geometry.contravariant3))
    return [
    (Covariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},0),
    (Covariant12Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},6),
    (Covariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (Contravariant123Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (Covariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},3),
    (Covariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (WVector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (Contravariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},0),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},0),
    (WVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},0),
    (WVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},4),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},9),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    ]
end

function method_info(FT, ::typeof(Geometry.Jcontravariant3))
    return [
    (Covariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},2),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},1),
    (Covariant12Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},7),
    (Covariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},4),
    (Covariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (Contravariant3Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},1),
    (Covariant12Vector{FT},FullLocalGeometry{(1,2,3),LatLongZPoint{FT},FT,SMatrix{3,3,FT,9}},4),
    (Covariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (Contravariant3Vector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},1),
    (WVector{FT},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},4),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},4),
    (AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(3,),ZPoint{FT},FT,SMatrix{1,1,FT,1}},2),
    (WVector{FT},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},10),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},4),
    (AxisTensor{FT,2,Tuple{ContravariantAxis{(3,)},CovariantAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    (WVector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},5),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},5),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},5),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},2),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},2),
    (Covariant1Vector{FT},FullLocalGeometry{(1,3),XZPoint{FT},FT,SMatrix{2,2,FT,4}},2),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},4),
    (AxisTensor{FT,2,Tuple{LocalAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},10),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(1,2)}},SMatrix{1,2,FT,2}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},4),
    (AxisTensor{FT,2,Tuple{CovariantAxis{(3,)},LocalAxis{(3,)}},SMatrix{1,1,FT,1}},FullLocalGeometry{(1,2,3),XYZPoint{FT},FT,SMatrix{3,3,FT,9}},2),
    ]
end

#! format: on
