#! format: off

# Short type aliases for LocalGeometry in method tables (5 type params: I, C, FT,
# Metric wrapping ∂x∂ξ, and precomputed gⁱʲ).
const LG_13_XZ{FT}    = LocalGeometry{(1,3),XZPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UWAxis,Covariant13Axis},SMatrix{2,2,FT,4}}},
    Tensor{2,FT,Tuple{Contravariant13Axis,Contravariant13Axis},SMatrix{2,2,FT,4}}}
const LG_123_XYZ{FT}  = LocalGeometry{(1,2,3),XYZPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UVWAxis,Covariant123Axis},SMatrix{3,3,FT,9}}},
    Tensor{2,FT,Tuple{Contravariant123Axis,Contravariant123Axis},SMatrix{3,3,FT,9}}}
const LG_123_LLZ{FT}  = LocalGeometry{(1,2,3),LatLongZPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UVWAxis,Covariant123Axis},SMatrix{3,3,FT,9}}},
    Tensor{2,FT,Tuple{Contravariant123Axis,Contravariant123Axis},SMatrix{3,3,FT,9}}}
const LG_12_XY{FT}    = LocalGeometry{(1,2),XYPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UVAxis,Covariant12Axis},SMatrix{2,2,FT,4}}},
    Tensor{2,FT,Tuple{Contravariant12Axis,Contravariant12Axis},SMatrix{2,2,FT,4}}}
const LG_3_Z{FT}      = LocalGeometry{(3,),ZPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{WAxis,Covariant3Axis},SMatrix{1,1,FT,1}}},
    Tensor{2,FT,Tuple{Contravariant3Axis,Contravariant3Axis},SMatrix{1,1,FT,1}}}
const LG_12_LL{FT}    = LocalGeometry{(1,2),LatLongPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UVAxis,Covariant12Axis},SMatrix{2,2,FT,4}}},
    Tensor{2,FT,Tuple{Contravariant12Axis,Contravariant12Axis},SMatrix{2,2,FT,4}}}
const LG_1_X{FT}      = LocalGeometry{(1,),XPoint{FT},FT,
    Metric{Tensor{2,FT,Tuple{UAxis,Covariant1Axis},SMatrix{1,1,FT,1}}},
    Tensor{2,FT,Tuple{Contravariant1Axis,Contravariant1Axis},SMatrix{1,1,FT,1}}}


function method_info(FT, ::typeof(Geometry.project))
    return [
    (Contravariant3Axis,Covariant3Vector{FT},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,Contravariant3Vector{FT},LG_13_XZ{FT}, 0),
    (Contravariant3Axis,Covariant3Vector{FT},LG_123_XYZ{FT}, 3),
    (Contravariant3Axis,Contravariant3Vector{FT},LG_123_XYZ{FT}, 0),
    (Contravariant3Axis,Contravariant123Vector{FT},LG_123_XYZ{FT}, 0),
    (Contravariant1Axis,Covariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (Contravariant2Axis,Covariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (Contravariant1Axis,Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Contravariant2Axis,Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Contravariant3Axis,Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Contravariant3Axis,Covariant3Vector{FT},LG_123_LLZ{FT}, 3),
    (Contravariant3Axis,Contravariant3Vector{FT},LG_123_LLZ{FT}, 0),
    (Contravariant1Axis,Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Contravariant2Axis,Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Contravariant3Axis,Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (Contravariant1Axis,Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (Contravariant2Axis,Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (Contravariant1Axis,UVVector{FT},LG_12_XY{FT}, 6),
    (Contravariant1Axis,Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_12_XY{FT}, 12),
    (Contravariant2Axis,UVVector{FT},LG_12_XY{FT}, 6),
    (Contravariant2Axis,Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_12_XY{FT}, 12),
    (Contravariant1Axis,Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Contravariant2Axis,Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Contravariant3Axis,Covariant3Vector{FT},LG_3_Z{FT}, 1),
    (Contravariant3Axis,WVector{FT},LG_3_Z{FT}, 1),
    (Contravariant3Axis,Contravariant3Vector{FT},LG_3_Z{FT}, 0),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_3_Z{FT}, 1),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 0),
    (Contravariant3Axis,WVector{FT},LG_123_XYZ{FT}, 3),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 0),
    (Contravariant1Axis,Covariant1Vector{FT},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Tensor{2,FT,Tuple{Covariant1Axis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Tensor{2,FT,Tuple{Covariant1Axis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,WVector{FT},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,UVector{FT},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{WAxis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Tensor{2,FT,Tuple{UAxis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Tensor{2,FT,Tuple{UAxis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Covariant13Vector{FT},LG_13_XZ{FT}, 6),
    (Contravariant3Axis,Covariant1Vector{FT},LG_13_XZ{FT}, 2),
    (Contravariant1Axis,Contravariant13Vector{FT},LG_13_XZ{FT}, 0),
    (Contravariant3Axis,Contravariant13Vector{FT},LG_13_XZ{FT}, 0),
    (Contravariant1Axis,Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Contravariant2Axis,Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Contravariant1Axis,Tensor{2,FT,Tuple{Covariant12Axis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Contravariant2Axis,Tensor{2,FT,Tuple{Covariant12Axis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Contravariant1Axis,UVVector{FT},LG_123_XYZ{FT}, 9),
    (Contravariant2Axis,UVVector{FT},LG_123_XYZ{FT}, 9),
    (Contravariant3Axis,Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Contravariant1Axis,Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Contravariant2Axis,Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Contravariant3Axis,Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 3),
    (Contravariant1Axis,Tensor{2,FT,Tuple{UVAxis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Contravariant2Axis,Tensor{2,FT,Tuple{UVAxis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Contravariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 3),
    (Contravariant1Axis,Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (Contravariant2Axis,Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (Contravariant1Axis,UVVector{FT},LG_12_LL{FT}, 6),
    (Contravariant2Axis,UVVector{FT},LG_12_LL{FT}, 6),
    (Contravariant1Axis,Contravariant12Vector{FT},LG_12_XY{FT}, 0),
    (Contravariant2Axis,Contravariant12Vector{FT},LG_12_XY{FT}, 0),
    # 2-argument method types
    # (Covariant12Axis,Covariant1Vector{FT},0),
    # (Covariant12Axis,Covariant12Vector{FT},0),
    # (Covariant12Axis,Covariant123Vector{FT},0),
    # (Covariant12Axis,Covariant13Vector{FT},0),
    # (Covariant12Axis,Tensor{2,FT,Tuple{Covariant1Axis,CartesianAxis{(1,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (Covariant12Axis,Tensor{2,FT,Tuple{Covariant13Axis,CartesianAxis{(1,)}},StaticArraysCore.SMatrix{2,1,FT,2},},,0),
    # (UVAxis,Tensor{2,FT,Tuple{UVWAxis,Covariant12Axis},StaticArraysCore.SMatrix{3,2,FT,6},},,0),
    # (UVAxis,UVVector{FT},0),
    # (Contravariant1Axis,Contravariant12Vector{FT},0),
    # (Contravariant2Axis,Contravariant12Vector{FT},0),
    # (Covariant123Axis,Covariant3Vector{FT},0),
    # (Contravariant3Axis,Contravariant123Vector{FT},0),
    # (Covariant3Axis,Covariant3Vector{FT},0),
    # (Contravariant3Axis,Contravariant3Vector{FT},0),
    # (WAxis,WVector{FT},0),
    # (Covariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant3Axis,UVAxis},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (WAxis,Tensor{2,FT,Tuple{WAxis,UVAxis},StaticArraysCore.SMatrix{1,2,FT,2},},,0),
    # (Covariant3Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant3Axis,WAxis},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (UVAxis,Tensor{2,FT,Tuple{UVAxis,UVAxis},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (Contravariant1Axis,Tensor{2,FT,Tuple{Contravariant12Axis,UVAxis},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (Contravariant2Axis,Tensor{2,FT,Tuple{Contravariant12Axis,UVAxis},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (Covariant123Axis,Covariant123Vector{FT},0),
    # (Contravariant1Axis,Contravariant123Vector{FT},0),
    # (Contravariant2Axis,Contravariant123Vector{FT},0),
    # (Covariant123Axis,Covariant12Vector{FT},0),
    # (Covariant13Axis,Covariant1Vector{FT},0),
    # (Contravariant1Axis,Contravariant13Vector{FT},0),
    # (Covariant13Axis,Tensor{2,FT,Tuple{Covariant1Axis,UAxis},SMatrix{1,1,FT,1},},,0),
    # (Contravariant1Axis,Tensor{2,FT,Tuple{Contravariant13Axis,UAxis},SMatrix{2,1,FT,2},},,0),
    # (Covariant13Axis,Tensor{2,FT,Tuple{Covariant1Axis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Contravariant1Axis,Tensor{2,FT,Tuple{Contravariant13Axis,WAxis},SMatrix{2,1,FT,2},},,0),
    # (UWAxis,WVector{FT},0),
    # (Contravariant3Axis,Contravariant13Vector{FT},0),
    # (UWAxis,UVector{FT},0),
    # (UWAxis,Tensor{2,FT,Tuple{WAxis,UAxis},SMatrix{1,1,FT,1},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant13Axis,UAxis},SMatrix{2,1,FT,2},},,0),
    # (UWAxis,Tensor{2,FT,Tuple{UAxis,UAxis},SMatrix{1,1,FT,1},},,0),
    # (UWAxis,Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant13Axis,WAxis},SMatrix{2,1,FT,2},},,0),
    # (UWAxis,Tensor{2,FT,Tuple{UAxis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Covariant13Axis,Tensor{2,FT,Tuple{Covariant3Axis,UAxis},SMatrix{1,1,FT,1},},,0),
    # (Covariant13Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Covariant13Axis,Covariant3Vector{FT},0),
    # (Covariant123Axis,Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4},},,0),
    # (Contravariant1Axis,Tensor{2,FT,Tuple{Contravariant123Axis,UVAxis},SMatrix{3,2,FT,6},},,0),
    # (Contravariant2Axis,Tensor{2,FT,Tuple{Contravariant123Axis,UVAxis},SMatrix{3,2,FT,6},},,0),
    # (Covariant123Axis,Tensor{2,FT,Tuple{Covariant12Axis,WAxis},SMatrix{2,1,FT,2},},,0),
    # (Contravariant1Axis,Tensor{2,FT,Tuple{Contravariant123Axis,WAxis},SMatrix{3,1,FT,3},},,0),
    # (Contravariant2Axis,Tensor{2,FT,Tuple{Contravariant123Axis,WAxis},SMatrix{3,1,FT,3},},,0),
    # (UVWAxis,WVector{FT},0),
    # (UVWAxis,UVVector{FT},0),
    # (UVWAxis,Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant123Axis,UVAxis},SMatrix{3,2,FT,6},},,0),
    # (UVWAxis,Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4},},,0),
    # (UVWAxis,Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Contravariant3Axis,Tensor{2,FT,Tuple{Contravariant123Axis,WAxis},SMatrix{3,1,FT,3},},,0),
    # (UVWAxis,Tensor{2,FT,Tuple{UVAxis,WAxis},SMatrix{2,1,FT,2},},,0),
    # (Covariant123Axis,Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2},},,0),
    # (Covariant123Axis,Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1},},,0),
    # (Covariant13Axis,Covariant13Vector{FT},0),
    # (WAxis,UWVector{FT},0),
    # (UAxis,UWVector{FT},0),
    ]
end

function method_info(FT, ::typeof(Geometry.transform))
    return [
    # 3-argument method
    (Covariant13Axis,UWVector{FT},LG_13_XZ{FT}, 6),
    (Contravariant13Axis,UWVector{FT},LG_13_XZ{FT}, 6),
    (UWAxis,Covariant13Vector{FT},LG_13_XZ{FT}, 6),
    (Covariant1Axis,UWVector{FT},LG_13_XZ{FT}, 6),
    (Covariant3Axis,Covariant3Vector{FT},LG_13_XZ{FT}, 0),
    (Contravariant13Axis,Covariant13Vector{FT},LG_13_XZ{FT}, 6),
    (Covariant123Axis,UVWVector{FT},LG_123_XYZ{FT}, 15),
    (Contravariant123Axis,Covariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (Covariant123Axis,UVWVector{FT},LG_123_LLZ{FT}, 15),
    (Contravariant123Axis,UVWVector{FT},LG_123_LLZ{FT}, 15),
    (UVWAxis,Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (Covariant12Axis,UVWVector{FT},LG_123_LLZ{FT}, 15),
    (Covariant3Axis,Covariant3Vector{FT},LG_123_LLZ{FT}, 0),
    (Contravariant123Axis,Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Covariant123Axis,Contravariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (UVWAxis,Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Covariant12Axis,Contravariant12Vector{FT},LG_12_XY{FT}, 6),
    (UVAxis,Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Covariant12Axis,UVVector{FT},LG_12_XY{FT}, 6),
    (Contravariant12Axis,Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Covariant3Axis,WVector{FT},LG_3_Z{FT}, 1),
    (Covariant3Axis,WVector{FT},LG_123_XYZ{FT}, 3),
    (WAxis,Covariant3Vector{FT},LG_13_XZ{FT}, 2),
    (UWAxis,Covariant1Vector{FT},LG_13_XZ{FT}, 2),
    (Covariant123Axis,Contravariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (UVWAxis,Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Covariant12Axis,UVWVector{FT},LG_123_XYZ{FT}, 15),
    (Covariant3Axis,Covariant3Vector{FT},LG_123_XYZ{FT}, 0),
    (WAxis,Covariant3Vector{FT},LG_123_XYZ{FT}, 3),
    (Covariant12Axis,UVVector{FT},LG_12_LL{FT}, 6),
    (Covariant12Axis,Contravariant12Vector{FT},LG_12_LL{FT}, 6),
    (UVAxis,Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (Contravariant12Axis,Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (UVWAxis,Contravariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Covariant1Axis,UVector{FT},LG_1_X{FT}, 1),
    (UVAxis,Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4}},LG_12_XY{FT}, 12),
    (UVAxis,Contravariant12Vector{FT},LG_12_XY{FT}, 6),
    (Contravariant12Axis,UVVector{FT},LG_12_XY{FT}, 6),
    # 2-argument method
    # (Covariant12Axis,Covariant1Vector{FT},0),
    # (Covariant12Axis,Covariant13Vector{FT},0),
    # (Covariant12Axis,Tensor{2,FT,Tuple{Covariant1Axis,CartesianAxis{(1,)}},StaticArraysCore.SMatrix{1,1,FT,1},},,0),
    # (Covariant12Axis,Tensor{2,FT,Tuple{Covariant13Axis,CartesianAxis{(1,)}},StaticArraysCore.SMatrix{2,1,FT,2},},,0),
    # (UVAxis,UVVector{FT},0),
    # (Covariant13Axis,Covariant1Vector{FT},0),
    # (UWAxis,UWVector{FT},0),
    # (Covariant1Axis,Covariant13Vector{FT},0),
    # (UWAxis,UVector{FT},0),
    # (Covariant13Axis,Covariant13Vector{FT},0),
    # (UWAxis,WVector{FT},0),
    # (Covariant3Axis,Covariant13Vector{FT},0),
    # (Covariant123Axis,Covariant12Vector{FT},0),
    # (UVWAxis,UVWVector{FT},0),
    # (Covariant12Axis,Covariant123Vector{FT},0),
    # (Covariant12Axis,Covariant12Vector{FT},0),
    # (UAxis,UVVector{FT},0),
    # (UAxis,UVector{FT},0),
    # (Covariant1Axis,Covariant1Vector{FT},0),
    # (WAxis,UVVector{FT},0),
    # (WAxis,WVector{FT},0),
    # (Covariant3Axis,Covariant3Vector{FT},0),
    # (Covariant12Axis,Covariant3Vector{FT},0),
    # (UVWAxis,UVVector{FT},0),
    # (Covariant123Axis,Covariant123Vector{FT},0),
    # (Covariant12Axis,Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (UVAxis,Tensor{2,FT,Tuple{UVAxis,UVAxis},StaticArraysCore.SMatrix{2,2,FT,4},},,0),
    # (Contravariant12Axis,Contravariant12Vector{FT},0),
    # (Covariant123Axis,Covariant3Vector{FT},0),
    # (Contravariant123Axis,Contravariant3Vector{FT},0),
    # (Contravariant123Axis,Contravariant123Vector{FT},0),
    # (UVWAxis,WVector{FT},0),
    # (Covariant3Axis,Covariant123Vector{FT},0),
    # (Covariant13Axis,Covariant3Vector{FT},0),
    # (WAxis,UWVector{FT},0),
    # (WAxis,UVWVector{FT},0),
    # (Contravariant13Axis,Contravariant13Vector{FT},0),
    # (Contravariant1Axis,Contravariant13Vector{FT},0),
    # (Contravariant3Axis,Contravariant13Vector{FT},0),
    # (UAxis,UWVector{FT},0),
    # (Contravariant123Axis,Contravariant12Vector{FT},0),
    # (Contravariant12Axis,Contravariant123Vector{FT},0),
    # (Contravariant3Axis,Contravariant123Vector{FT},0),
    # (UVAxis,UVWVector{FT},0),
    # (UWAxis,UVVector{FT},0),
    # (Contravariant12Axis,Contravariant2Vector{FT},0),
    # (Covariant13Axis,Covariant12Vector{FT},0),
    # (UVAxis,UWVector{FT},0),
    ]
end


function method_info(FT, ::typeof(Geometry.contravariant1))
    return [
    (Covariant123Vector{FT},LG_13_XZ{FT}, 9),
    (Covariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (UVVector{FT},LG_12_XY{FT}, 6),
    (Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_12_XY{FT}, 12),
    (Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Covariant1Vector{FT},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant1Axis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant1Axis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (UVector{FT},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{UAxis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{UAxis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Covariant13Vector{FT},LG_13_XZ{FT}, 6),
    (Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Tensor{2,FT,Tuple{Covariant12Axis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (UVVector{FT},LG_123_XYZ{FT}, 9),
    (Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Tensor{2,FT,Tuple{UVAxis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (UVVector{FT},LG_12_LL{FT}, 6),
    (Contravariant12Vector{FT},LG_12_XY{FT}, 0),
    ]
end

function method_info(FT, ::typeof(Geometry.contravariant2))
    return [
    (Covariant123Vector{FT},LG_123_XYZ{FT}, 15),
    (Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Covariant123Vector{FT},LG_123_LLZ{FT}, 15),
    (Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (UVVector{FT},LG_12_XY{FT}, 6),
    (Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_12_XY{FT}, 12),
    (Covariant12Vector{FT},LG_12_XY{FT}, 6),
    (Tensor{2,FT,Tuple{Covariant12Axis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Tensor{2,FT,Tuple{Covariant12Axis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (UVVector{FT},LG_123_XYZ{FT}, 9),
    (Tensor{2,FT,Tuple{UVAxis,UVAxis},SMatrix{2,2,FT,4}},LG_123_XYZ{FT}, 18),
    (Tensor{2,FT,Tuple{UVAxis,WAxis},SMatrix{2,1,FT,2}},LG_123_XYZ{FT}, 9),
    (Covariant12Vector{FT},LG_12_LL{FT}, 6),
    (UVVector{FT},LG_12_LL{FT}, 6),
    (Contravariant12Vector{FT},LG_12_XY{FT}, 0),
    ]
end

function method_info(FT, ::typeof(Geometry.contravariant3))
    return [
    (Covariant3Vector{FT},LG_13_XZ{FT}, 2),
    (Contravariant3Vector{FT},LG_13_XZ{FT}, 0),
    (Covariant12Vector{FT},LG_13_XZ{FT}, 5),
    (Covariant3Vector{FT},LG_123_XYZ{FT}, 3),
    (Contravariant3Vector{FT},LG_123_XYZ{FT}, 0),
    (Contravariant123Vector{FT},LG_123_XYZ{FT}, 0),
    (Covariant12Vector{FT},LG_123_XYZ{FT}, 9),
    (Covariant3Vector{FT},LG_123_LLZ{FT}, 3),
    (Contravariant3Vector{FT},LG_123_LLZ{FT}, 0),
    (Covariant12Vector{FT},LG_123_LLZ{FT}, 9),
    (Covariant3Vector{FT},LG_3_Z{FT}, 1),
    (WVector{FT},LG_3_Z{FT}, 1),
    (Contravariant3Vector{FT},LG_3_Z{FT}, 0),
    (Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_3_Z{FT}, 1),
    (Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 0),
    (WVector{FT},LG_123_XYZ{FT}, 3),
    (Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 0),
    (WVector{FT},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{WAxis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant3Axis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 2),
    (Covariant1Vector{FT},LG_13_XZ{FT}, 2),
    (Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 3),
    (Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 6),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 3),
    ]
end

function method_info(FT, ::typeof(Geometry.Jcontravariant3))
    return [
    (Covariant3Vector{FT},LG_13_XZ{FT}, 3),
    (Contravariant3Vector{FT},LG_13_XZ{FT}, 1),
    (Covariant12Vector{FT},LG_13_XZ{FT}, 6),
    (Covariant3Vector{FT},LG_123_XYZ{FT}, 4),
    (Contravariant3Vector{FT},LG_123_XYZ{FT}, 1),
    (Covariant12Vector{FT},LG_123_XYZ{FT}, 10),
    (Covariant3Vector{FT},LG_123_LLZ{FT}, 4),
    (Contravariant3Vector{FT},LG_123_LLZ{FT}, 1),
    (Covariant12Vector{FT},LG_123_LLZ{FT}, 10),
    (Covariant3Vector{FT},LG_3_Z{FT}, 2),
    (Contravariant3Vector{FT},LG_3_Z{FT}, 1),
    (WVector{FT},LG_3_Z{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 4),
    (Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 4),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_3_Z{FT}, 2),
    (Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 4),
    (Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_3_Z{FT}, 2),
    (WVector{FT},LG_123_XYZ{FT}, 4),
    (Tensor{2,FT,Tuple{Covariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 8),
    (Tensor{2,FT,Tuple{Contravariant3Axis,Covariant12Axis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 2),
    (WVector{FT},LG_13_XZ{FT}, 3),
    (Tensor{2,FT,Tuple{WAxis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 3),
    (Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 3),
    (Tensor{2,FT,Tuple{Covariant3Axis,UAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 3),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_13_XZ{FT}, 3),
    (Covariant1Vector{FT},LG_13_XZ{FT}, 3),
    (Tensor{2,FT,Tuple{WAxis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 8),
    (Tensor{2,FT,Tuple{WAxis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 4),
    (Tensor{2,FT,Tuple{Covariant3Axis,UVAxis},SMatrix{1,2,FT,2}},LG_123_XYZ{FT}, 8),
    (Tensor{2,FT,Tuple{Covariant3Axis,WAxis},SMatrix{1,1,FT,1}},LG_123_XYZ{FT}, 4),
    ]
end

#! format: on
