# A pipeline for downstream performance checks
agents:
  queue: clima
  slurm_time: 14:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  COUPLER_PATH: ".buildkite/perf/ClimaCoupler.jl"
  CONFIG_PATH: "$COUPLER_PATH/config/nightly_configs"
  BENCHMARK_CONFIG_PATH: "$COUPLER_PATH/config/benchmark_configs"

timeout_in_minutes: 840

steps:
  - label: "Ensure submodule is checked out"
    command:
      - git submodule update --init --recursive .buildkite/perf/ClimaCoupler.jl
    key: "init_submodule"

  - label: "Check if pipeline should run :mag:"
    key: "check_changes"
    depends_on: "init_submodule"
    command:
      - |
        # Check if files in src, ext, or .buildkite/perf have changed
        if git diff --quiet origin/main...HEAD -- src ext .buildkite/perf; then
          echo "⏭️  No relevant changes detected, skipping downstream checks"
          buildkite-agent meta-data set "run-perf-checks" "false"
        else
          echo "✅ Relevant changes detected, running downstream checks"
          buildkite-agent meta-data set "run-perf-checks" "true"
        fi

  - label: "init :GPU:"
    key: "init_gpu_env"
    depends_on: "check_changes"
    if: "buildkite-agent meta-data get run-perf-checks"
    command:
      - "echo $$JULIA_DEPOT_PATH"
      - echo "--- Instantiate AMIP env"
      # Instantiate and dev install ClimaCore
      - "julia --project=$COUPLER_PATH/experiments/ClimaEarth/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - 'julia --project=$COUPLER_PATH/experiments/ClimaEarth/ -e ''using Pkg; Pkg.develop(path=".")'''
      - "julia --project=$COUPLER_PATH/experiments/ClimaEarth/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=$COUPLER_PATH/experiments/ClimaEarth/ -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: AMIP
    steps:
      - label: "Flagship AMIP GPU with prognostic EDMF + 1M + integrated land (16 helems)"
        key: "gpu_amip_progedmf_1M_land_he16"
        if: "buildkite-agent meta-data get run-perf-checks"
        command: "srun julia --threads=3 --color=yes --project=$COUPLER_PATH/experiments/ClimaEarth/ $COUPLER_PATH/experiments/ClimaEarth/run_amip.jl --config_file $BENCHMARK_CONFIG_PATH/amip_progedmf_1m_land_he16.yml --job_id gpu_amip_progedmf_1M_land_he16"
        artifact_paths: "output/gpu_amip_progedmf_1M_land_he16/artifacts/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_ntasks: 1
          slurm_mem: 16GB

  - wait

  - label: "Check SYPD for flagship AMIP"
    key: "check_amip_sypd"
    depends_on: "gpu_amip_progedmf_1M_land_he16"
    if: "buildkite-agent meta-data get run-perf-checks"
    command:
      - echo "--- Checking SYPD from artifacts"
      - |
        MIN_SYPD=0.079
        SYPD=$(cat output/gpu_amip_progedmf_1M_land_he16/artifacts/sypd.txt)
        echo "SYPD: $SYPD"
        if (( $(echo "$SYPD < $MIN_SYPD" | bc -l) )); then
          echo "❌ SYPD ($SYPD) is below threshold ($MIN_SYPD)"
          exit 1
        else
          echo "✅ SYPD ($SYPD) meets threshold ($MIN_SYPD)"
        fi
    agents:
      slurm_cpus_per_task: 1
