# A pipeline for downstream performance checks
agents:
  queue: clima
  slurm_time: 14:00:00
  modules: climacommon/2025_05_15

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  GKSwstype: 100
  SLURM_KILL_BAD_EXIT: 1
  COUPLER_PATH: ".buildkite/perf/ClimaCoupler.jl"
  COUPLER_CONFIG_PATH: "$COUPLER_PATH/config/benchmark_configs"
  LAND_PATH: ".buildkite/perf/ClimaLand.jl"

timeout_in_minutes: 840

steps:
  - label: "Initialize ClimaCoupler"
    key: "init_coupler"
    command:
      - git clone https://github.com/CliMA/ClimaCoupler.jl.git $COUPLER_PATH
      - |
        julia --project=$COUPLER_PATH/experiments/AMIP/ -e '
          using Pkg
          Pkg.Registry.update()
          Pkg.instantiate(; verbose = true)
          Pkg.precompile()
          Pkg.status()'
    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - label: "Initialize ClimaLand"
    key: "init_land"
    command:
      - git clone https://github.com/CliMA/ClimaLand.jl.git $LAND_PATH
      - |
        julia --project=$LAND_PATH -e '
          using Pkg
          Pkg.Registry.update()
          Pkg.instantiate(; verbose = true)
          Pkg.precompile()
          Pkg.status()'
    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - label: "Flagship AMIP GPU with prognostic EDMF + 1M + integrated land (16 helems)"
    key: "gpu_amip_progedmf_1M_land_he16"
    depends_on: "init_coupler"
    command:
      - julia --project=$COUPLER_PATH/experiments/AMIP/ -e 'using Pkg; Pkg.add("ClimaCore#main")'
      - srun julia --threads=3 --color=yes --project=$COUPLER_PATH/experiments/AMIP/ $COUPLER_PATH/experiments/AMIP/run_simulation.jl --config_file $COUPLER_CONFIG_PATH/amip_progedmf_1m_land_he16.yml --job_id gpu_amip_progedmf_1M_land_he16

      - echo "--- Checking SYPD from artifacts (main branch)"
      - bash .buildkite/perf/check-perf.sh output/gpu_amip_progedmf_1M_land_he16/artifacts/sypd.txt

      - julia --project=$COUPLER_PATH/experiments/AMIP/ -e 'using Pkg; Pkg.dev(; path = ".")'
      - srun julia --threads=3 --color=yes --project=$COUPLER_PATH/experiments/AMIP/ $COUPLER_PATH/experiments/AMIP/run_simulation.jl --config_file $COUPLER_CONFIG_PATH/amip_progedmf_1m_land_he16.yml --job_id gpu_amip_progedmf_1M_land_he16

      - echo "--- Checking SYPD from artifacts (PR branch)"
      - bash .buildkite/perf/check-perf.sh output/gpu_amip_progedmf_1M_land_he16/artifacts/sypd.txt
    artifact_paths: "output/gpu_amip_progedmf_1M_land_he16/artifacts/*"
    env:
      CLIMACOMMS_DEVICE: "CUDA"
      MIN_PERCENT_CHANGE: "-5"
    agents:
      slurm_gpus_per_task: 1
      slurm_cpus_per_task: 4
      slurm_ntasks: 1
      slurm_mem: 16GB

  - label: "Flagship snowy land model GPU (soil + canopy + snow)"
    key: "gpu_climaland_snowy_land"
    depends_on: "init_land"
    command:
      - julia --project=$LAND_PATH -e 'using Pkg; Pkg.add("ClimaCore#main")'
      - srun bash .buildkite/perf/run-land-benchmark.sh $LAND_PATH snowy_land

      - echo "--- Checking SYPD from artifacts (main branch)"
      - bash .buildkite/perf/check-perf.sh snowy_land_benchmark_gpu/sims_per_second.txt

      - julia --project=$LAND_PATH -e 'using Pkg; Pkg.dev(; path = ".")'
      - srun bash .buildkite/perf/run-land-benchmark.sh $LAND_PATH snowy_land

      - echo "--- Checking SYPD from artifacts (PR branch)"
      - bash .buildkite/perf/check-perf.sh snowy_land_benchmark_gpu/sims_per_second.txt
    artifact_paths: "snowy_land_benchmark_gpu/*"
    env:
      CLIMACOMMS_DEVICE: "CUDA"
      MIN_PERCENT_CHANGE: "-5"
    agents:
      slurm_gpus_per_task: 1
      slurm_cpus_per_task: 4
      slurm_ntasks: 1
      slurm_mem: 16GB
