"""
    DataScope(A)
    DataScope(args...)

Singleton type that represents a computational unit responsible for updating the
values in an `AbstractArray` of type `A`. It can also be constructed from an
instance of an array or any similarly indexable argument, or by combining the
`DataScope`s of multiple arguments (always selecting the smallest scope).

# Extended help

`DataScope`s can be compared using [`is_subscope`](@ref), and they define
methods for the following functions:

  - [`partition`](@ref).
  - [`num_threads`](@ref) or [`num_partitions`](@ref) (only one needs a method).
  - [`thread_rank`](@ref) or [`partition_rank`](@ref) (only one needs a method).
  - [`parallelize_over`](@ref) and [`synchronize`](@ref).
  - [`scoped_array`](@ref) and [`scoped_static_array`](@ref).
  - [`strided_access`](@ref).

Every [`DataLayout`](@ref) is assigned a specific `DataScope`, but the scope of
a generic `AbstractArray` must be inferred from its type. While some types of
arrays can only be assigned to one scope (e.g., a `StaticArray` can only be
accessed from [`ThisThread`](@ref)), this is not always the case. For example, a
`SubArray` view of a `CUDA.CuDeviceArray` that serves as the parent of a
`DataLayout` inside a GPU kernel can be assigned to many different scopes:

  - `ThisKernel`, if the `DataLayout` was generated by [`level`](@ref),
    [`slab`](@ref), [`column`](@ref), or a single-point `view`.
  - Either `ThisBlock`, `ThisSubBlock`, or `ThisThread`, if it was generated by
    [`foreach_level`](@ref), [`foreach_slab`](@ref), or [`foreach_column`](@ref).
  - `ThisThread`, if it was generated by [`foreach_point`](@ref).

In general, the `DataScope` of a non-`DataLayout` array includes all threads
that are able to access it, so the `SubArray` in the example above is assigned
to `ThisKernel`. If a smaller scope is required, the array must be wrapped in a
`DataLayout`.
"""
abstract type DataScope end

DataScope(::A) where {A <: AbstractArray} = DataScope(A)
DataScope(::Type{<:Array}) = ThisThreadPool()
DataScope(::Type{<:StaticArrays.StaticArray}) = ThisThread()
DataScope(::Type{<:SubArray{<:Any, <:Any, A}}) where {A} = DataScope(A)
DataScope(::Type{<:Base.ReshapedArray{<:Any, <:Any, A}}) where {A} = DataScope(A)

# Infer parent types of other AbstractArrays (constant-folding not guaranteed).
DataScope(::Type{A}) where {A <: AbstractArray} = DataScope(return_type(parent, Tuple{A}))

# Scope errors are singleton exception types whose messages are only generated
# by showerror on the host. Interpolating the scope types into a message where
# the error is thrown would require calling a @generated function, which cannot
# always be compiled for GPUs.
struct NonOverlappingScopesError{S1, S2} <: Exception end
NonOverlappingScopesError(::S1, ::S2) where {S1, S2} =
    NonOverlappingScopesError{S1, S2}()
Base.showerror(io::IO, ::NonOverlappingScopesError{S1, S2}) where {S1, S2} =
    print(
        io,
        "$S1 and $S2 do not overlap, so they cannot be put in the same \
         DataScope",
    )

struct InvalidSubscopeError{S1, S2} <: Exception end
InvalidSubscopeError(::S1, ::S2) where {S1, S2} =
    InvalidSubscopeError{S1, S2}()
Base.showerror(io::IO, ::InvalidSubscopeError{S1, S2}) where {S1, S2} =
    print(io, "$S1 is not a subset of $S2")

DataScope(scope1::DataScope, scope2::DataScope) =
    is_subscope(scope1, scope2) ? scope1 :
    is_subscope(scope2, scope1) ? scope2 :
    throw(NonOverlappingScopesError(scope1, scope2))

@inline DataScope(arg1, arg2, args...) =
    unrolled_mapreduce(DataScope, DataScope, (arg1, arg2, args...))

"""
    partition(scope)

Return a [`DataScope`](@ref) whose threads are a subset of `scope`. This is a
statically inferrable, device-agnostic generalization of the `tiled_partition`
function from CUDA's `cooperative_groups` extension. By default, the entire
scope is placed in a single partition.
"""
partition(scope) = scope

"""
    is_subscope(subscope, scope)

Return whether `subscope` is equal to the [`DataScope`](@ref) `scope`, or is a
[`partition`](@ref) of it, or a partition of a partition, and so on.
"""
@inline is_subscope(subscope, scope) =
    subscope == scope ||
    partition(scope) != scope && is_subscope(subscope, partition(scope))

@noinline throw_invalid_subscope(subscope, scope) =
    throw(InvalidSubscopeError(subscope, scope))

# Ranks and counts keep the integer type of the scope's threads (UInt32 on GPUs,
# which emulate 64-bit integer arithmetic, and whose unsigned divisions by a
# power of two are shifts), so the literals here take that type.
@inline function num_subscopes(subscope, scope)
    n = num_threads(scope)
    subscope == scope && return one(n)
    is_subscope(subscope, scope) &&
        return fld(n - one(n), oftype(n, num_threads(subscope))) + one(n)
    throw_invalid_subscope(subscope, scope)
end
@inline function subscope_rank(subscope, scope)
    rank = thread_rank(scope)
    subscope == scope && return one(rank)
    is_subscope(subscope, scope) &&
        return fld(rank - one(rank), oftype(rank, num_threads(subscope))) + one(rank)
    throw_invalid_subscope(subscope, scope)
end

"""
    num_threads(scope)

Return the number of threads that are part of a [`DataScope`](@ref).
"""
@inline num_threads(scope) = num_partitions(scope) * num_threads(partition(scope))

"""
    static_num_threads(scope)

Return the [`num_threads`](@ref) of a [`DataScope`](@ref) when it is a
compile-time constant, and `nothing` when it is only known at run time. Used by
[`register_similar`](@ref) to determine how many points of a slice each thread
can be assigned.
"""
static_num_threads(scope) = nothing

# Number of threads that a device launch must give each of its launch units (a
# thread block on a GPU) when a loop assigns every slice to a subscope of the
# launch's scope: max_threads rounded down to a whole multiple of
# num_threads(subscope), and never fewer than one whole subscope.
#
# WHOLE SUBSCOPES INVARIANT: a slice loop gives the thread of rank r the
# strided subset r:num_threads(subscope):Np of a slice's points, with the
# stride read from the subscope's *type*: in a partial subscope, points
# assigned to a missing rank are silently skipped, and the point-to-register
# correspondence of a register_similar destination breaks. Every launch unit
# must therefore hold a whole number of subscopes, and max_threads must be at
# least num_threads(subscope), which holds on supported devices.
@inline function subscope_launch_threads(subscope, max_threads)
    subscope_threads = Int(num_threads(subscope))
    return max(fld(Int(max_threads), subscope_threads), 1) * subscope_threads
end

"""
    num_partitions(scope)

Return the number of partitions (results of [`partition`](@ref)) in a
[`DataScope`](@ref).
"""
@inline num_partitions(scope) = num_subscopes(partition(scope), scope)

"""
    thread_rank(scope)

Return an integer between 1 and [`num_threads`](@ref) that identifies the calling
thread within a [`DataScope`](@ref).
"""
@inline function thread_rank(scope)
    partition_rank_ = partition_rank(scope)
    return (partition_rank_ - one(partition_rank_)) * num_threads(partition(scope)) +
           thread_rank(partition(scope))
end

"""
    partition_rank(scope)

Return an integer between 1 and [`num_partitions`](@ref) that identifies the
calling thread's partition within a [`DataScope`](@ref).
"""
@inline partition_rank(scope) = subscope_rank(partition(scope), scope)

"""
    parallelize_over(f, scope)

Call `f()` from each thread in a [`DataScope`](@ref). Code that appears outside
of this instruction is not necessarily parallelized over all available threads.
"""
parallelize_over(f::F, _) where {F} = f()

"""
    synchronize(scope)

Synchronize all threads in a [`DataScope`](@ref), so that no thread can begin
executing code that comes after this instruction until all other threads have
finished executing the code that came before it.
"""
synchronize(scope) =
    isone(num_threads(scope)) || throw(ArgumentError(invalid_sync_string(scope)))
@generated invalid_sync_string(scope) = "Cannot synchronize all threads in $scope"

# View of a per-task buffer that holds each thread or block's result during a reduction.
# Allocating a new array for every reduction is slower than the reduction itself, so one
# buffer per array and element type is kept for the lifetime of the task that reduces.
# The buffer only ever grows, and reductions on a task run one after another, so no two
# live views of it overlap.
function task_reduction_buffer(::Type{A}, required_length::Int) where {A}
    storage = current_task().storage
    stored_buffers =
        isnothing(storage) ? nothing :
        get(storage::IdDict{Any, Any}, :climacore_reduction_buffers, nothing)
    # The type assertion keeps every use of the dictionary below statically dispatched.
    buffers =
        isnothing(stored_buffers) ?
        task_local_storage(:climacore_reduction_buffers, IdDict{Any, Any}()) :
        stored_buffers::IdDict{Any, Any}
    buffer = get(buffers, A, nothing)
    if isnothing(buffer) || length(buffer::A) < required_length
        # Start at a length that covers the thread and block counts of typical reductions,
        # so that a buffer is not reallocated every time a larger reduction comes along.
        buffer = similar(A, max(required_length, 1024))
        buffers[A] = buffer
    end
    return view(buffer::A, Base.OneTo(required_length))
end

"""
    scoped_array(scope, T, dims; [buffer])

Return an array with element type `T` and size `dims`, whose values can be modified
by every thread in a [`DataScope`](@ref). When `buffer = true`, a task-local buffer
is reused instead of allocating a new array; the default is `buffer = false`.
"""
scoped_array(scope, ::Type{T}, dims; buffer = false) where {T} =
    throw(ArgumentError(invalid_allocation_string(scope)))
@generated invalid_allocation_string(scope) = "Cannot allocate array for $scope"

"""
    scoped_static_array(scope, T, dims)

Return a statically sized array with element type `T` and size `dims`, whose values
can be modified by every thread in a [`DataScope`](@ref). If a `DataScope` does not
provide its own method, this falls back to calling [`scoped_array`](@ref).

Two allocations with equal element types and sizes may be assigned to the same
memory (this is what happens for block-level allocations on GPUs, which are
stored in shared memory), so their lifetimes must not overlap unless they are
guaranteed to hold identical values.
"""
scoped_static_array(scope, ::Type{T}, dims) where {T} = scoped_array(scope, T, dims)

"""
    strided_access(scope)

Return whether [`subscope_indices`](@ref) should return a strided range of
indices for the given [`DataScope`](@ref), rather than a contiguous range. The
default is `true`.
"""
strided_access(scope) = true

"""
    ThisThread()

[`DataScope`](@ref) that represents the currently running thread.
"""
struct ThisThread <: DataScope end

num_threads(::ThisThread) = 1
static_num_threads(::ThisThread) = 1
thread_rank(::ThisThread) = 1
scoped_array(::ThisThread, ::Type{T}, dims; buffer = false) where {T} =
    buffer ? task_reduction_buffer(Array{T, 1}, dims) : Array{T}(undef, dims)
scoped_static_array(::ThisThread, ::Type{T}, dims) where {T} =
    StaticArrays.MArray{Tuple{dims...}, T}(undef)

"""
    ThisThreadPool()

[`DataScope`](@ref) that represents threads from the default thread pool on a CPU.

Loops that run at the same time divide the pool between them, with each loop's
share of the pool determined by [`resolve_pool_threads`](@ref) when it starts. A
loop that cannot claim more than one thread — because the pool is busy, because
Julia was started with a single thread, or because the loop is nested in a
multithreaded loop located outside of ClimaCore — runs on the thread that
launched it.
"""
struct ThisThreadPool <: DataScope end

# Threads._nthreads_in_pool is two pointer loads of jl_n_threads_per_pool; the public
# Threads.threadpoolsize wraps _sym_to_tpid, whose unreachable ArgumentError branch has
# a runtime dispatch (via repr/sprint) that JET flags on Julia 1.10+. The default pool is
# pool ID 1 in _sym_to_tpid; fall back to the public API if the internals change.
@static if isdefined(Threads, :_nthreads_in_pool)
    default_pool_size() = Int(Threads._nthreads_in_pool(Int8(1)))
else
    default_pool_size() = Threads.threadpoolsize(:default)
end

# Threads are launched individually, rather than with Threads.threading_run, because a loop
# is only given part of the pool when other loops are using the rest of it. This also keeps
# ClimaCore's own loops from entering a threaded region, so that running_in_threaded_loop
# detects threaded loops from outside of ClimaCore and nothing else. The threads must be
# spawned into the default pool explicitly, since a plain Task inherits the pool of the
# task that creates it, which may be the interactive pool.
#
# Like parallelize_over, this is a function barrier: @nospecialize gives every
# loop body a single shared method instance, which is what keeps compile time
# from scaling with the number of distinct loops. It costs one dynamic call per
# loop launch, which is negligible beside the Threads.@spawn calls below.
# @nospecialize alone only shares the compiled code; inference still infers one
# instance per loop body type, so @nospecializeinfer shares the inference too.
Base.@nospecializeinfer @noinline function launch_pool_threads(@nospecialize(f), n::Int)
    tasks = Vector{Task}(undef, n)
    for rank in Base.OneTo(n)
        @inbounds tasks[rank] = Threads.@spawn :default begin
            task_local_storage(:climacore_pool_threads, ($rank, $n))
            f()
        end
    end
    # Like Threads.threading_run, wait for every thread before returning or throwing, so
    # that none of the loop's threads are still running when its claim on them is released.
    for task in tasks
        try
            wait(task)
        catch
        end
    end
    failed_tasks = filter!(istaskfailed, tasks)
    isempty(failed_tasks) ||
        throw(CompositeException(map(TaskFailedException, failed_tasks)))
    return nothing
end

running_in_threaded_loop() = !iszero(ccall(:jl_in_threaded_region, Cint, ()))

# The rank and thread count of the loop the current task is running, if any. Storage is
# nothing until first set, so storage-less tasks are never running a pool loop. A rank of 0
# means the task launches a pool loop rather than being one of its threads.
function pool_thread_info()
    storage = current_task().storage
    isnothing(storage) && return (0, 0)
    return get(storage::IdDict{Any, Any}, :climacore_pool_threads, (0, 0))::NTuple{2, Int}
end

# Threads the current pool loop was given, which is the whole pool when the loop was
# started with an explicit scope instead of a resolved one. The thread count used to launch
# a loop must match the one used to divide up its indices, so both go through this.
pool_loop_threads() = (n = pool_thread_info()[2]; n > 0 ? n : default_pool_size())

partition(::ThisThreadPool) = ThisThread()
num_threads(::ThisThreadPool) = pool_loop_threads()
thread_rank(::ThisThreadPool) = max(pool_thread_info()[1], 1)
# Both this and launch_pool_threads are function barriers: @noinline keeps the
# loop body out of the caller, and @nospecialize compiles a single method
# instance for every loop body instead of one per closure type. Unlike the
# per-slab barrier ruled out in scoped_slice_loop, this barrier is crossed once
# per loop launch rather than once per slice, so its dynamic dispatch is
# amortized against the Threads.@spawn calls that immediately follow it, while
# the compile-time saving applies to every distinct loop in the program.
Base.@nospecializeinfer @noinline parallelize_over(@nospecialize(f), ::ThisThreadPool) =
    iszero(pool_thread_info()[1]) ? launch_pool_threads(f, pool_loop_threads()) :
    throw(ArgumentError("Nested loops over ThisThreadPool are not supported"))

# Concurrent loops divide the pool between them, instead of letting whichever loop claims
# it first run on every thread while the rest run on one thread each and become stragglers.
# Each loop takes an equal share of the pool, so a loop that finds the pool busy waits for
# the next loop rather than oversubscribing it. Loops are short, so the shares of a set of
# concurrent loops converge after the first of them finishes.
const POOL_THREADS_IN_USE = Threads.Atomic{Int}(0)
const PENDING_POOL_LOOPS = Threads.Atomic{Int}(0)

# Number of threads claimed, which is 0 when the loop has to run on the calling thread. A
# loop stays counted in PENDING_POOL_LOOPS either way, so that loops which start later can
# see how many ways the pool still needs to be divided.
function claim_pool_threads()
    pool_size = default_pool_size()
    pending = Threads.atomic_add!(PENDING_POOL_LOOPS, 1) + 1
    # Multithreaded loops cannot be nested in each other, and a pool of one thread has
    # nothing to divide up.
    (isone(pool_size) || running_in_threaded_loop()) && return 0
    share = max(1, pool_size ÷ pending)
    while true
        in_use = POOL_THREADS_IN_USE[]
        n = min(share, pool_size - in_use)
        n > 1 || return 0
        Threads.atomic_cas!(POOL_THREADS_IN_USE, in_use, in_use + n) == in_use && return n
    end
end

"""
    resolve_pool_threads()

Return the number of threads from the default thread pool that the current loop may
use, which is 1 when the loop has to run on the thread that started it. A loop that
is given more than one thread records the count in task-local storage, so that
[`num_threads`](@ref) and [`thread_rank`](@ref) report the same division of the
loop's indices for as long as it runs.

Every loop that calls this must give its threads back with
[`release_pool_threads`](@ref) once it has finished.

The count is not returned as a [`DataScope`](@ref), and `jl_in_threaded_region` is
only read here, once per loop. A scope whose type is only known at run time becomes
a union in every call below it, and reading the process-global threaded-region flag
more than once per loop lets an unrelated task flip it in between; either would keep
pointwise loops from staying allocation free.
"""
function resolve_pool_threads()
    pool_thread_info() == (0, 0) ||
        throw(ArgumentError("Nested loops over ThisThreadPool are not supported"))
    n = claim_pool_threads()
    # Only a loop that takes threads from the pool records anything: a loop that runs on the
    # thread that started it never reads num_threads or thread_rank, and writing to
    # task-local storage would allocate in every loop that does not need it.
    iszero(n) || task_local_storage(:climacore_pool_threads, (0, n))
    return iszero(n) ? 1 : n
end

"""
    release_pool_threads()

Give back the threads that [`resolve_pool_threads`](@ref) claimed for the current
loop, and return `nothing`. Every loop that resolves a [`ThisThreadPool`](@ref) must
call this once it has finished, whether or not it was given any threads.
"""
function release_pool_threads()
    n = pool_thread_info()[2]
    if n > 1
        task_local_storage(:climacore_pool_threads, (0, 0))
        Threads.atomic_sub!(POOL_THREADS_IN_USE, n)
    end
    Threads.atomic_sub!(PENDING_POOL_LOOPS, 1)
    return nothing
end

scoped_array(::ThisThreadPool, ::Type{T}, dims; buffer = false) where {T} =
    buffer ? task_reduction_buffer(Array{T, 1}, dims) : Array{T}(undef, dims)
strided_access(::ThisThreadPool) = false # Always use contiguous ranges on CPUs.

"""
    VALIDATE_LAUNCH_CONFIGURATIONS

When `true`, device extensions cross-check every kernel launch configuration
they compute against their device API's occupancy calculator. Disabled by
default, so that a tie broken differently on an untested device degrades
performance instead of crashing a simulation; device tests enable it.
"""
const VALIDATE_LAUNCH_CONFIGURATIONS = Ref(false)

"""
    subscope_indices(subscope, scope, indices)

Return the part of `indices` (either linear or Cartesian) assigned to the calling
`subscope` when the indices are divided among the subscopes of a [`DataScope`](@ref).
The result is a strided range if [`strided_access`](@ref) is `true` for `scope`, or
a contiguous range if it is `false`.

Contiguous ranges are generated by partitioning the indices into chunks whose
lengths differ from each other by at most 1, which guarantees that every subset
of the scope gets a nonempty chunk whenever there are at least as many indices
as subsets. In contrast, always assigning `cld(length(indices), n_subsets)`
indices to each subset can lead to one or more empty subsets.
"""
Base.@propagate_inbounds function subscope_indices(subscope, scope, indices)
    subscope == scope && return indices
    rank =
        subscope == partition(scope) ? partition_rank(scope) :
        subscope_rank(subscope, scope)
    n =
        subscope == partition(scope) ? num_partitions(scope) :
        num_subscopes(subscope, scope)
    view_range =
        strided_access(scope) ? strided_range(rank, n, length(indices)) :
        (length(indices) * (rank - 1) ÷ n + 1):(length(indices) * rank ÷ n)
    return subscope_index_view(scope, indices, view_range)
end

# AbstractRange of the integers start, start + step, start + 2 step, ... that
# are at most stop (the Ints of start:step:stop), stored by its bound rather
# than by its length. Base's StepRange divides its endpoints by its step when it
# is constructed and every time its length is read, and a slice loop reads the
# length of its range at least once per nested loop; only the outermost loop's
# step is not a compile-time constant -- the loop every other one runs inside.
# GPUs have no integer division unit, so each such division expands into a long
# emulation sequence (about twenty instructions for 32 bits, over a hundred for
# 64), which is as much as the rest of a single-operator kernel; hosts divide
# out of order and once per slice rather than per point, which is why the
# divisions are invisible in CPU timings. Iterating the range (see iterate
# below) compares each value with the bound instead of counting, so the length
# is only divided out where a caller asks for it (bounds checks and nested
# subsets). Keeping the bound rather than the length also lets the compiler
# bound the trip count of the loops of a slice with no more points than its
# scope has threads: every thread then reaches the bound after its first point,
# which turns such a loop into straight-line code.
#
# Invariants: start >= 1, step >= 1, stop >= 0, and stop + step fits in the
# integer type (see the strided_range constructor below), so that the arithmetic
# in iterate is exact.
struct StridedRange{I <: Integer} <: AbstractRange{I}
    start::I
    step::I
    stop::I
end
@inline Base.first(range::StridedRange) = range.start
@inline Base.step(range::StridedRange) = range.step
@inline Base.isempty(range::StridedRange) = range.start > range.stop
# The number of values, divided out of the bound; the step is never zero, so
# the division skips the zero check of ÷, which adds a branch to an exception
# (the offset is nonnegative, so an unsigned division is exact).
@inline function strided_length(range::StridedRange{I}) where {I}
    isempty(range) && return zero(I)
    return Base.udiv_int(range.stop - range.start, range.step) + one(I)
end
@inline Base.length(range::StridedRange) = Int(strided_length(range))
@inline Base.size(range::StridedRange) = (length(range),)
@inline Base.last(range::StridedRange{I}) where {I} =
    range.start + (strided_length(range) - one(I)) * range.step
Base.@propagate_inbounds function Base.getindex(
    range::StridedRange{I},
    i::Integer,
) where {I}
    @boundscheck checkbounds(range, i)
    return range.start + (i % I - one(I)) * range.step
end
# Iteration without the length: a value is followed by the next one unless
# that exceeds the bound.
@inline Base.iterate(range::StridedRange) =
    isempty(range) ? nothing : (range.start, range.start)
@inline function Base.iterate(range::StridedRange{I}, i::I) where {I}
    next = i + range.step
    next <= range.stop || return nothing
    return (next, next)
end

# Range subsets of strided ranges, taken by nested slice loops and views of
# views. Every range subindex must be covered by one of these methods: a missed
# pair falls back to the generic AbstractArray getindex, which allocates a
# Vector and interpolates an error string, neither of which is GPU-compilable.
# The subsets keep the integer type of the strided range, whose values all fit
# in it, so that index arithmetic stays in 32 bits on GPUs. The bound of a
# subset is the bound of the positions it selects (which for a strided subset
# is its own bound, so that nested loops need no division), mapped into the
# range and clipped to the range's bound; the product is formed in 64 bits
# because an unclipped bound can exceed the integer type.
@inline position_bound(sub::StridedRange) = sub.stop
@inline position_bound(sub::AbstractRange) = last(sub)
Base.@propagate_inbounds function Base.getindex(
    range::StridedRange{I}, sub::AbstractRange{<:Integer},
) where {I}
    @boundscheck checkbounds(range, sub)
    start = range.start + (first(sub) % I - one(I)) * range.step
    unclipped_stop = Int(range.start) + (Int(position_bound(sub)) - 1) * Int(range.step)
    stop = max(min(unclipped_stop, Int(range.stop)), 0) % I
    return StridedRange(start, range.step * (step(sub) % I), stop)
end
# Restricted to the unit range types of CartesianIndices and views (an
# AbstractUnitRange signature is ambiguous with BlockArrays' blocked ranges).
Base.@propagate_inbounds function Base.getindex(
    range::Union{Base.OneTo{<:Integer}, UnitRange{<:Integer}}, sub::StridedRange{I},
) where {I}
    @boundscheck checkbounds(range, sub)
    offset = first(range) % I - one(I)
    stop = max(min(sub.stop + offset, last(range) % I), zero(I))
    return StridedRange(sub.start + offset, sub.step, stop)
end

# The strided subset rank:n:n_indices, in the integer type of rank and n. GPU
# scopes have UInt32 ranks, and their launches check that the number of indices
# fits in 31 bits, which leaves room for the step (see the invariants of
# StridedRange).
@inline strided_range(rank::I, n::I, n_indices) where {I <: Integer} =
    StridedRange(rank, n, n_indices % I)
@inline strided_range(rank, n, n_indices) =
    strided_range(promote(rank, n)..., n_indices)
# Return a view by default, so iterating over it is as efficient as iterating
# over the original indices. GPU scopes must override this, since a strided view
# of CartesianIndices is a ReshapedArray with GPU-incompatible bounds checks.
Base.@propagate_inbounds subscope_index_view(scope, indices, view_range) =
    view(indices, view_range)

struct StridedCartesianIndices{N, I, V} <: AbstractVector{CartesianIndex{N}}
    indices::I
    view_range::V
end
StridedCartesianIndices(indices::CartesianIndices{N}, view_range) where {N} =
    StridedCartesianIndices{N, typeof(indices), typeof(view_range)}(indices, view_range)
Base.size(strided::StridedCartesianIndices) = (length(strided.view_range),)
Base.@propagate_inbounds Base.getindex(strided::StridedCartesianIndices, n::Integer) =
    single_axis_cartesian_index(strided.indices, strided.view_range[n])

# Linear-to-Cartesian conversion without divisions when at most one axis has
# more than one index (every loop over the points of a column or over levels):
# the linear index is the position along that axis. In kernels, the axis
# lengths come from the layout types and are compile-time constants, so the
# test folds; otherwise, this falls back to Base's division per axis.
@inline function single_axis_cartesian_index(indices::CartesianIndices, index)
    ranges = indices.indices
    unrolled_sum(range -> Int(!isone(length(range))), ranges) <= 1 ||
        return @inbounds indices[cartesian_index_from_linear(size(indices), index)]
    return CartesianIndex(
        unrolled_map(
            range ->
                isone(length(range)) ? first(range) :
                Int(first(range) % typeof(index) + index - one(index)),
            ranges,
        ),
    )
end
