"""
    DataScope(A)
    DataScope(args...)

Singleton type that represents a computational unit responsible for updating the
values in an `AbstractArray` of type `A`. May also be constructed using an
instance of an array or any similarly indexable argument, or by combining the
`DataScope`s from multiple arguments (always selecting the smallest scope).

`DataScope`s can be compared using [`is_subscope`](@ref), and they define
methods for the following functions:
 - [`partition`](@ref)
 - [`num_threads`](@ref) or [`num_partitions`](@ref) (only need to define one)
 - [`thread_rank`](@ref) or [`partition_rank`](@ref) (only need to define one)
 - [`parallelize_over`](@ref) and [`synchronize`](@ref)
 - [`scoped_array`](@ref) and [`scoped_static_array`](@ref)
 - [`strided_access`](@ref)

# Extended help

`DataScope`s are device-agnostic generalizations of "cooperative groups"
from the [`CG`](https://cuda.juliagpu.org/stable/development/kernel/#Cooperative-groups)
module in `CUDA.jl`, which are built on top of the `cooperative_groups`
[extension](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#cooperative-groups)
that comes prepackaged with CUDA. They are used throughout ClimaCore to track
ownership of data across different levels of parallelization.

Every [`DataLayout`](@ref) is assigned a specific `DataScope`, but the scope of
a generic `AbstractArray` must be inferred from its type. While some types of
arrays can only be assigned to one scope (e.g., a `StaticArray` can only be
accessed from [`ThisThread`](@ref)), this is not always the case. For example, a
`SubArray` view of a `CUDA.CuDeviceArray` that serves as the parent of a
`DataLayout` inside a GPU kernel can be assigned to many different scopes:
 - `ThisKernel`, if the `DataLayout` was generated by [`level`](@ref),
   [`slab`](@ref), [`column`](@ref), or a single-point `view`
 - Either `ThisBlock`, `ThisSubBlock`, or `ThisThread`, if it was generated by
   [`foreach_level`](@ref), [`foreach_slab`](@ref), or [`foreach_column`](@ref)
 - `ThisThread`, if it was generated by [`foreach_point`](@ref)

In general, the `DataScope` of a non-`DataLayout` array will include all threads
that are able to access it, so the `SubArray` in the example above would be
assigned to `ThisKernel`. If a smaller scope is required, the array needs to be
wrapped in a `DataLayout`.
"""
abstract type DataScope end

DataScope(::A) where {A <: AbstractArray} = DataScope(A)
DataScope(::Type{<:StaticArrays.StaticArray}) = ThisThread()
DataScope(::Type{<:Array}) = ThisThreadPool()
DataScope(::Type{A}) where {A <: AbstractArray} = DataScope(return_type(parent, Tuple{A}))

DataScope(arg1, arg2, args...) =
    unrolled_reduce(unrolled_map(DataScope, (arg1, arg2, args...))) do scope1, scope2
        is_subscope(scope1, scope2) ? scope1 :
        is_subscope(scope2, scope1) ? scope2 :
        throw(ArgumentError(non_overlapping_scopes_string(scope1, scope2)))
    end
@generated non_overlapping_scopes_string(::S1, ::S2) where {S1, S2} =
    "$S1 and $S2 do not overlap, so they cannot be put in the same DataScope"

"""
    partition(scope)

[`DataScope`](@ref) whose threads are a subset of the specified scope. Acts as a
statically inferrable, device-agnostic generalization of the `tiled_partition`
function from CUDA's `cooperative_groups` extension. By default, the entire
scope is placed in a single partition.
"""
partition(scope) = scope

"""
    is_subscope(subscope, scope)

Checks if one [`DataScope`](@ref) is equal to another scope, or if it is a
[`partition`](@ref) of the scope, or a partition of a partition, and so on.
"""
is_subscope(subscope, scope) =
    subscope == scope ||
    partition(scope) != scope && is_subscope(subscope, partition(scope))

num_subscopes(subscope, scope) =
    subscope == scope ? 1 :
    is_subscope(subscope, scope) ? cld(num_threads(scope), num_threads(subscope)) :
    throw(ArgumentError(invalid_subscope_string(subscope, scope)))
subscope_rank(subscope, scope) =
    subscope == scope ? 1 :
    is_subscope(subscope, scope) ? fld(thread_rank(scope) - 1, num_threads(subscope)) + 1 :
    throw(ArgumentError(invalid_subscope_string(subscope, scope)))
@generated invalid_subscope_string(::S1, ::S2) where {S1, S2} = "$S1 is not a subset of $S2"

"""
    num_threads(scope)

Number of threads that are part of a [`DataScope`](@ref).
"""
num_threads(scope) = num_partitions(scope) * num_threads(partition(scope))

"""
    num_partitions(scope)

Number of partitions (results of [`partition`](@ref)) in a [`DataScope`](@ref).
"""
num_partitions(scope) = num_subscopes(partition(scope), scope)

"""
    thread_rank(scope)

Integer between 1 and [`num_threads`](@ref) used to identify each thread that is
part of a [`DataScope`](@ref).
"""
thread_rank(scope) =
    (partition_rank(scope) - 1) * num_threads(partition(scope)) +
    thread_rank(partition(scope))

"""
    partition_rank(scope)

Integer between 1 and [`num_partitions`](@ref) used to identify each partition
of a [`DataScope`](@ref).
"""
partition_rank(scope) = subscope_rank(partition(scope), scope)

"""
    parallelize_over(f, scope)

Calls `f()` from each thread in a [`DataScope`](@ref). Code that appears outside
of this instruction is not necessarily parallelized over all available threads.
"""
parallelize_over(f::F, _) where {F} = f()

"""
    synchronize(scope)

Synchronizes all threads in a [`DataScope`](@ref), so that no thread can begin
executing code that comes after this instruction until all other threads have
finished executing the code that came before this instruction.
"""
synchronize(scope) =
    isone(num_threads(scope)) || throw(ArgumentError(invalid_sync_string(scope)))
@generated invalid_sync_string(scope) = "Cannot synchronize all threads in $scope"

"""
    scoped_array(scope, T, dims)

Array with the specified element type and size, whose values can be modified by
every thread in a [`DataScope`](@ref).
"""
scoped_array(scope, ::Type{T}, dims) where {T} =
    throw(ArgumentError(invalid_allocation_string(scope)))
@generated invalid_allocation_string(scope) = "Cannot allocate array for $scope"

"""
    scoped_static_array(scope, T, dims)

Statically-sized array with the specified element type and size, whose values
can be modified by every thread in a [`DataScope`](@ref). If a `DataScope` does
not provide its own method, this falls back to calling [`scoped_array`](@ref).
"""
scoped_static_array(scope, ::Type{T}, dims) where {T} = scoped_array(scope, T, dims)

"""
    strided_access(scope)

Determines whether [`subscope_indices`](@ref) should return a strided range of
indices for the given [`DataScope`](@ref), rather than a contiguous range. By
default, this is always true.
"""
strided_access(scope) = true

"""
    ThisThread()

[`DataScope`](@ref) that represents the currently running thread.
"""
struct ThisThread <: DataScope end

num_threads(::ThisThread) = 1
thread_rank(::ThisThread) = 1
scoped_array(::ThisThread, ::Type{T}, dims) where {T} = Array{T}(undef, dims)
scoped_static_array(::ThisThread, ::Type{T}, dims) where {T} =
    StaticArrays.MArray{Tuple{dims...}, T}(undef)

"""
    ThisThreadPool()

[`DataScope`](@ref) that represents all available threads on a CPU.
"""
struct ThisThreadPool <: DataScope end

partition(::ThisThreadPool) = ThisThread()
num_threads(::ThisThreadPool) = Threads.nthreads()
thread_rank(::ThisThreadPool) = Threads.threadid()
parallelize_over(f::F, ::ThisThreadPool) where {F} =
    iszero(ccall(:jl_in_threaded_region, Cint, ())) ? # same logic as `@threads :static ...`
    Threads.threading_run(_ -> f(), true) :
    throw(ArgumentError("ThisThreadPool cannot be used in a loop annotated with @threads"))

scoped_array(::ThisThreadPool, ::Type{T}, dims) where {T} = Array{T}(undef, dims)
strided_access(::ThisThreadPool) = false # Always use contiguous ranges on CPUs.

"""
    subscope_indices(subscope, scope, indices)

Divides a collection of indices (either linear or Cartesian) among subsets of a
[`DataScope`](@ref). The result is a strided range if [`strided_access`](@ref)
is true for `scope`, or a contiguous range if it is false.
"""
Base.@propagate_inbounds function subscope_indices(subscope, scope, indices)
    subscope == scope && return indices
    rank =
        subscope == ThisThread() ? thread_rank(scope) :
        subscope == partition(scope) ? partition_rank(scope) :
        subscope_rank(subscope, scope)
    n =
        subscope == ThisThread() ? num_threads(scope) :
        subscope == partition(scope) ? num_partitions(scope) :
        num_subscopes(subscope, scope)
    N = length(indices)
    contiguous_range = ((rank - 1) * cld(N, n) + 1):min(rank * cld(N, n), N)
    return view(indices, strided_access(scope) ? (rank:n:N) : contiguous_range)
end
