"""
    parent_array_type(A, [B])

Determines the array type underlying the wrapper type `A`, dropping all
parameters related to array dimensions. A new basetype `B` can be specified to
replace the original `eltype(A)`.
"""
parent_array_type(::Type{A}) where {A} = parent_array_type(A, eltype(A))
parent_array_type(::Type{<:Array}, ::Type{B}) where {B} = Array{B}
parent_array_type(::Type{<:MArray}, ::Type{B}) where {B} = MArray{<:Any, B}
parent_array_type(::Type{<:SubArray{<:Any, <:Any, A}}, ::Type{B}) where {A, B} =
    parent_array_type(A, B)
parent_array_type(
    ::Type{<:Base.ReshapedArray{<:Any, <:Any, A}},
    ::Type{B},
) where {A, B} = parent_array_type(A, B)

"""
    promote_parent_array_type(A1, A2)

Promotes two array types `A1` and `A2` generated by [`parent_array_type`](@ref),
which includes promoting the basetypes `eltype(A1)` and `eltype(A2)`.
"""
promote_parent_array_type(::Type{Array{B1}}, ::Type{Array{B2}}) where {B1, B2} =
    Array{promote_type(B1, B2)}
promote_parent_array_type(
    ::Type{MArray{<:Any, B1}},
    ::Type{MArray{<:Any, B2}},
) where {B1, B2} = MArray{<:Any, promote_type(B1, B2)}
promote_parent_array_type(
    ::Type{MArray{<:Any, B1}},
    ::Type{Array{B2}},
) where {B1, B2} = MArray{<:Any, promote_type(B1, B2)}
promote_parent_array_type(
    ::Type{Array{B1}},
    ::Type{MArray{<:Any, B2}},
) where {B1, B2} = MArray{<:Any, promote_type(B1, B2)}

# Wrap fieldtypes in Vals to force inlining and unrolling of recursive functions
@inline fieldtype_vals(::Type{T}) where {T} =
    ntuple(Val ∘ Base.Fix1(fieldtype, T), Val(fieldcount(T)))

@noinline throw_not_immutable(::Type{T}) where {T} =
    throw(ArgumentError(lazy"Cannot compute storage size of mutable type $T"))

# Unrolled analogue of Base.packedsize (with GPU support, unlike Base version)
@inline storage_size(::Type{T}) where {T} = _storage_size(Val(T))
@inline _storage_size(::Val{T}) where {T} =
    Base.issingletontype(T) || iszero(fieldcount(T)) ? sizeof(T) :
    isbitstype(T) ? unrolled_mapreduce(_storage_size, +, fieldtype_vals(T)) :
    throw_not_immutable(T)

@inline default_basetype_size(::Type{T}) where {T} =
    _default_basetype_size(Val(T))
@inline _default_basetype_size(::Val{T}) where {T} =
    Base.issingletontype(T) || iszero(fieldcount(T)) ? sizeof(T) :
    unrolled_mapreduce(_default_basetype_size, gcd, fieldtype_vals(T))

@inline default_basetype_or_nothing(::Type{T}) where {T} =
    Base.issingletontype(T) ? Nothing :
    _default_basetype_or_nothing(Val(T), Val(T))
@inline _default_basetype_or_nothing(::Val{B}, ::Val{T}) where {B, T} =
    sizeof(B) == default_basetype_size(T) ? B :
    Base.issingletontype(B) || iszero(fieldcount(B)) ? nothing :
    unrolled_mapreduce(
        Base.Fix2(_default_basetype_or_nothing, Val(T)),
        (option1, option2) -> isnothing(option2) ? option1 : option2,
        fieldtype_vals(B),
    )

@inline uint_type_for_size(::Val{1}) = UInt8
@inline uint_type_for_size(::Val{2}) = UInt16
@inline uint_type_for_size(::Val{4}) = UInt32
@inline uint_type_for_size(::Val{8}) = UInt64
@inline uint_type_for_size(::Val{16}) = UInt128

"""
    default_basetype(T)

Recursively searches through the `fieldtypes` of `T` for a type that
[`set_struct!`](@ref) and [`get_struct`](@ref) can use to represent all other
types nested in `T`. If no such type is found, an unsigned integer type is
selected based on the size of `T`.
"""
@inline function default_basetype(::Type{T}) where {T}
    B = default_basetype_or_nothing(T)
    return isnothing(B) ? uint_type_for_size(Val(default_basetype_size(T))) : B
end

# Avoid using Bools to represent non-Bools, since 7 of 8 bits are zeroed out for
# padding, e.g., Core.bitcast(UInt8, Core.bitcast(Bool, 0x02)) == 0x00
@inline contains_any_bools(::Type{T}) where {T} = _contains_any_bools(Val(T))
@inline _contains_any_bools(::Val{T}) where {T} =
    T <: Bool || unrolled_any(_contains_any_bools, fieldtype_vals(T))
@inline contains_only_bools(::Type{T}) where {T} = _contains_only_bools(Val(T))
@inline _contains_only_bools(::Val{T}) where {T} =
    iszero(fieldcount(T)) ? T <: Bool || Base.issingletontype(T) :
    unrolled_all(_contains_only_bools, fieldtype_vals(T))

@inline is_valid_basetype(::Type{B}, ::Type{T}) where {B, T} =
    Base.issingletontype(B) ? Base.issingletontype(T) :
    iszero(storage_size(T) % storage_size(B)) &&
    (!contains_any_bools(B) || contains_only_bools(T))

@generated storage_size_string(::Type{T}) where {T} =
    "$(storage_size(T)) \
     $(storage_size(T) != sizeof(T) ? "non-padding " : "")bytes"
@generated wrong_storage_type_string(::Type{B}, ::Type{T}) where {B, T} =
    "Cannot convert value of type $T ($(storage_size_string(T))) into values \
     of type $B ($(storage_size_string(B)))"
@noinline throw_wrong_storage_type(::Type{B}, ::Type{T}) where {B, T} =
    throw(ArgumentError(wrong_storage_type_string(B, T)))

"""
    check_basetype(B, T)

Checks if [`set_struct!`](@ref) and [`get_struct`](@ref) can use values of type
`B` to store values of type `T`. Throws an error if `B` is not a valid basetype,
printing out one `fieldtype` of `T` that cannot use `B` as a basetype.
"""
@inline function check_basetype(::Type{B}, ::Type{T}) where {B, T}
    is_valid_basetype(B, T) && return nothing
    iszero(fieldcount(T)) && throw_wrong_storage_type(B, T)
    F = unrolled_findfirst(Base.Fix1(!is_valid_basetype, B), fieldtypes(T))
    return check_basetype(B, fieldtype(T, F))
end

"""
    checked_valid_basetype(B, T)

Returns either `B` or the [`default_basetype`](@ref) of `T`, depending on
whether `B` is a valid basetype for `T`.
"""
@inline checked_valid_basetype(::Type{B}, ::Type{T}) where {B, T} =
    is_valid_basetype(B, T) ? B : default_basetype(T)

"""
    storage_length(B, T)

Determines how many values of type `B` are required by [`set_struct!`](@ref) and
[`get_struct`](@ref) to store a single value of type `T`.
"""
@inline storage_length(::Type{B}, ::Type{T}) where {B, T} =
    is_valid_basetype(B, T) ?
    (Base.issingletontype(B) ? sizeof(B) : storage_size(T) ÷ storage_size(B)) :
    throw_wrong_storage_type(B, T)

@noinline function throw_wrong_storage_length(
    ::Type{B},
    ::Type{T},
    num_Bs,
) where {B, T}
    smaller_length, larger_length = minmax(num_Bs, storage_length(B, T))
    throw(BoundsError(1:smaller_length, larger_length))
end # Is there a more verbose alternative to this error that is GPU-compatible?

@inline check_storage_length(::Type{B}, ::Type{T}, num_Bs) where {B, T} =
    storage_length(B, T) == num_Bs ? nothing :
    throw_wrong_storage_length(B, T, num_Bs)

"""
    struct_field_view(array, T, Val(F), [Val(D)])

Creates a view of the data in `array` that corresponds to a particular field of
`T`, assuming that `array` has been populated by [`set_struct!`](@ref). The
field is specified through a `Val` that contains its index `F`, and it can be
loaded from the resulting view using [`get_struct`](@ref).

For multidimensional arrays with values of type `T` stored along a particular
dimension, the resulting view contains the specified field from each value. By
default, it is assumed that each value is stored along the last dimension, but
any other dimension can be specified through a `Val` containing its index `D`.
"""
@inline function struct_field_view(
    array,
    ::Type{T},
    ::Val{F},
    ::Val{D} = Val(ndims(array)),
) where {T, F, D}
    @boundscheck check_storage_length(eltype(array), T, size(array, D))
    num_D_indices = storage_length(eltype(array), fieldtype(T, F))
    last_D_index = storage_length(eltype(array), Tuple{fieldtypes(T)[1:F]...})
    D_indices = (last_D_index - num_D_indices + 1):last_D_index
    all_indices = Base.setindex(axes(array), D_indices, D)
    @boundscheck checkbounds(array, all_indices...)
    return Base.unsafe_view(array, all_indices...)
end

@inline function struct_indices(array, ::Type{T}) where {T}
    @boundscheck check_storage_length(eltype(array), T, length(array))
    @boundscheck checkbounds(array, 1:length(array))
    return StaticOneTo(storage_length(eltype(array), T))
end
@inline function struct_indices(
    array,
    ::Type{T},
    start::Integer,
    ::Val{D} = Val(ndims(array)),
) where {T, D}
    @boundscheck check_storage_length(eltype(array), T, size(array, D))
    step = prod(size(array)[1:(D - 1)])
    @boundscheck checkbounds(array, range(start; step, length = size(array, D)))
    one_to_length = StaticOneTo(storage_length(eltype(array), T))
    return unrolled_map(i -> start + (i - 1) * step, one_to_length)
end
@inline function struct_indices(
    array,
    ::Type{T},
    start::CartesianIndex,
    ::Val{D} = Val(ndims(array)),
) where {T, D}
    @boundscheck check_storage_length(eltype(array), T, size(array, D))
    full_start_tuple = (Tuple(start)[1:(D - 1)]..., 1, Tuple(start)[D:end]...)
    full_start = CartesianIndex(full_start_tuple)
    full_stop = Base.setindex(full_start, size(array, D), D)
    @boundscheck checkbounds(array, full_start:full_stop)
    one_to_length = StaticOneTo(storage_length(eltype(array), T))
    return unrolled_map(i -> Base.setindex(full_start, i, D), one_to_length)
end

@static if VERSION < v"1.12"
    struct _Fix1{F, A}
        f::F
        arg::A
    end
    @inline ((; f, arg)::_Fix1)(args...) = f(arg, args...)
else
    const _Fix1 = Base.Fix1 # Fix1 works for multiple arguments as of Julia 1.12
end

"""
    set_struct!(array, struct_val, [start], [Val(D)])

Populates `array` with data that represents `struct_val`, using
[`bitcast_struct`](@ref) to convert `struct_val` into elements of the array.

For multidimensional arrays with values of type `T` stored along a particular
dimension, a `start` index is used to specify where to store `struct_val`. By
default, each value is stored along the last dimension, but any other dimension
can be specified through a `Val` containing its index `D`.

# Examples

```julia-repl
julia> set_struct!(zeros(Int8, 4), Int32(1))
4-element Vector{Int8}:
 1
 0
 0
 0

julia> set_struct!(zeros(Int64, 3), (Int32(2), Int32(0), Int128(1)))
3-element Vector{Int64}:
 2
 1
 0

julia> set_struct!(zeros(Int64, 2, 3), (Int32(2), Int32(0), Int128(1)), 2)
2×3 Matrix{Int64}:
 0  0  0
 2  1  0
```
"""
@generated set_struct!(array, struct_val::T, start...) where {T} = quote
    Base.@_propagate_inbounds_meta
    indices = struct_indices(array, T, start...)
    NTupleOfBs = NTuple{length(indices), eltype(array)}
    array_vals = bitcast_struct(NTupleOfBs, struct_val)
    unrolled_foreach(_Fix1(Base.unsafe_setindex!, array), array_vals, indices)
    return array
end # Make this a generated function to guarantee type stability on Julia 1.10

"""
    get_struct(array, T, [start], [Val(D)])

Loads a value of type `T` that [`set_struct!`](@ref) has stored in `array`,
using [`bitcast_struct`](@ref) to convert elements of the array into a value of
type `T`.

As with `set_struct!`, a `start` index and an optional dimension index `D` can
be used to select a single value from an array that contains multiple values.

# Examples

```julia-repl
julia> get_struct(Int8[1, 0, 0, 0], Int32)
1

julia> get_struct([2, 1, 0], Tuple{Int32, Int32, Int128})
(2, 0, 1)

julia> get_struct([0 0 0; 2 1 0], Tuple{Int32, Int32, Int128}, 2)
(2, 0, 1)
```
"""
@generated get_struct(array, ::Type{T}, start...) where {T} = quote
    Base.@_propagate_inbounds_meta
    indices = struct_indices(array, T, start...)
    array_vals = unrolled_map(Base.Fix1(Base.unsafe_getindex, array), indices)
    return bitcast_struct(T, array_vals)
end # Make this a generated function to guarantee type stability on Julia 1.10

if hasfield(Method, :recursion_relation)
    for f in (
        _storage_size,
        _default_basetype_size,
        _default_basetype_or_nothing,
        _contains_any_bools,
        _contains_only_bools,
    )
        for m in methods(f)
            m.recursion_relation = Returns(true)
        end
    end # Disable recursion limits to guarantee type stability on Julia 1.10
end
