import Adapt
import CUDA
import ClimaComms
import ClimaCore: DataLayouts

include("scopes.jl")
include("loops.jl")
include("data_layouts_threadblock.jl")

# Kernel parameters are limited to 4 KiB of memory before compute capability
# 7.0, and a SubArray of a 5-D CuDeviceArray uses 128-160 of those bytes per
# broadcast argument (64 for the parent array, 48-80 for the index ranges, and
# 16 for precomputed linear-indexing fields), so broadcasts over a few dozen
# field views cannot be launched as kernels. Since every extent of the array in
# a DataLayout is either available from the layout's type or identical to the
# corresponding extent of the parent array, the index ranges can be replaced
# with an Int32 offset for every restricted dimension, plus an Int32 extent for
# every restricted dimension whose extent is not available from the type. The
# type parameters are the extent of each dimension `E` (with 0 for extents that
# are only available at runtime), the restricted dimensions `R`, and the tuple
# lengths `K = length(R)` and `D = count(d -> iszero(E[d]), R)`.
struct CompactDeviceView{T, N, E, R, K, D, A <: AbstractArray{T, N}} <:
       AbstractArray{T, N}
    parent::A
    offsets::NTuple{K, Int32}
    dynamic_extents::NTuple{D, Int32}
end

Base.parent(array::CompactDeviceView) = array.parent

DataLayouts.DataScope(
    ::Type{<:CompactDeviceView{<:Any, <:Any, <:Any, <:Any, <:Any, <:Any, A}},
) where {A} = DataLayouts.DataScope(A)

@inline Base.size(array::CompactDeviceView{<:Any, N, E, R}) where {N, E, R} =
    ntuple(Val(N)) do d
        iszero(E[d]) || return Int(E[d])
        d in R || return size(parent(array), d)
        return Int(array.dynamic_extents[count(r -> r <= d && iszero(E[r]), R)])
    end

# Index into the parent array that corresponds to an index into the view,
# shifted by the stored offset along each restricted dimension
@inline parent_index(array::CompactDeviceView{<:Any, N, <:Any, R}, index) where {N, R} =
    ntuple(Val(N)) do d
        position = findfirst(==(d), R)
        isnothing(position) ? index[d] : index[d] + Int(array.offsets[position])
    end

Base.@propagate_inbounds function Base.getindex(
    array::CompactDeviceView{<:Any, N},
    index::Vararg{Integer, N},
) where {N}
    @boundscheck checkbounds(array, index...)
    return @inbounds parent(array)[parent_index(array, index)...]
end

Base.@propagate_inbounds function Base.setindex!(
    array::CompactDeviceView{<:Any, N},
    value,
    index::Vararg{Integer, N},
) where {N}
    @boundscheck checkbounds(array, index...)
    @inbounds parent(array)[parent_index(array, index)...] = value
    return array
end

# Index types generated by stable_view for unrestricted and restricted
# dimensions of the parent array in a DataLayout
const ViewDimIndex = Union{
    Base.Slice{<:Base.OneTo{<:Integer}},
    Base.OneTo{<:Integer},
    UnitRange{<:Integer},
}

# Extent of every parent array dimension that is available from a DataLayout's
# type, with 0 for dimensions whose extents are only available at runtime
@inline inferred_parent_extents(data, array) = DataLayouts.add_f_dim(
    map(extent -> something(extent, 0), DataLayouts.inferred_size(data)),
    DataLayouts.num_basetypes(eltype(array), eltype(data)),
    Val(DataLayouts.f_dim(data)),
)

compact_device_view(array, data) = array

@inline function compact_device_view(
    array::SubArray{<:Any, N, <:CUDA.CuDeviceArray, <:NTuple{N, ViewDimIndex}},
    data::DataLayouts.DataLayout,
) where {N}
    extents = inferred_parent_extents(data, array)
    length(extents) == N ||
        throw(DimensionMismatch("DataLayout extents do not match its array"))
    indices = parentindices(array)
    restricted =
        filter(d -> indices[d] isa UnitRange, ntuple(identity, Val(N)))
    dynamic = filter(d -> iszero(extents[d]), restricted)
    array = CompactDeviceView{
        eltype(array),
        N,
        extents,
        restricted,
        length(restricted),
        length(dynamic),
        typeof(parent(array)),
    }(
        parent(array),
        map(d -> Int32(first(indices[d]) - 1), restricted),
        map(d -> Int32(length(indices[d])), dynamic),
    )
    # Validates every extent assumption at launch time, including that any
    # Base.OneTo indices span their full parent dimensions
    size(array) == size(array) ||
        throw(DimensionMismatch("DataLayout extents do not match its array"))
    return array
end

Adapt.adapt_structure(to::CUDA.KernelAdaptor, data::DataLayouts.DataLayout) =
    DataLayouts.rebuild(
        data,
        compact_device_view(Adapt.adapt(to, parent(data)), data),
    )
