name: ClimaCoreTempestRemap CI
on:
  pull_request:

jobs:
  lib-climacore-tempestremap:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.10'
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install Julia dependencies
        run: >
          julia --project=monorepo -e 'using Pkg; Pkg.develop(path="$(pwd())"); Pkg.develop(path="$(pwd())/lib/ClimaCoreTempestRemap")'
      - name: Run the tests
        continue-on-error: true
        env:
            CI_OUTPUT_DIR: output
        run: >
          julia --project=monorepo -e 'using Pkg; Pkg.test("ClimaCoreTempestRemap")'
          && echo "TESTS_SUCCESSFUL=true" >> $GITHUB_ENV
      - name: Upload test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: climacore-tempestremap-output
          path: |
            lib/ClimaCoreTempestRemap/test/output
      - name: Fail after artifacts if tests failed
        if: ${{ env.TESTS_SUCCESSFUL != 'true' }}
        run: exit 1
