name: CodeCov

on:
  push:
    tags: '*'
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.9

    - name: Test with coverage
      run: |
        julia --project -e 'using Pkg; Pkg.instantiate()'
        julia --project -e 'using Pkg; Pkg.test(coverage=true)'

    - name: Generate coverage file
      run: julia --project -e 'using Pkg; Pkg.add("Coverage");
                               using Coverage;
                               LCOV.writefile("coverage-lcov.info", Codecov.process_folder())'
      if: success()

    - name: Submit coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
      if: success()

